-- parity/recommendations.sql
-- The compat view must reproduce the legacy table EXACTLY. Zero rows from every statement = pass.
-- The legacy side lists the ORIGINAL 41 columns by name: the expand migrations append columns to the legacy table
-- (e.g. LINKED_CANONICAL_PLAYER_ID) and the app never selects them, so `SELECT *` would compare the wrong shape.
-- ${LEGACY_SUFFIX} is empty before the swap (legacy table is PLAYER_RECOMMENDATIONS) and '_LEGACY' after it.

SELECT 'recommendations: row counts differ' AS CHECK_NAME, l.N AS LEGACY_ROWS, v.N AS VIEW_ROWS
FROM (SELECT COUNT(*) AS N FROM ${CORE}.PLAYER_RECOMMENDATIONS${LEGACY_SUFFIX}) l,
     (SELECT COUNT(*) AS N FROM ${CORE}.V_COMPAT_PLAYER_RECOMMENDATIONS) v
WHERE l.N <> v.N;

SELECT 'recommendations: columns differ in name or order' AS CHECK_NAME, a.ORDINAL_POSITION, a.COLUMN_NAME AS LEGACY_COLUMN, b.COLUMN_NAME AS VIEW_COLUMN
FROM (SELECT ORDINAL_POSITION, COLUMN_NAME FROM ${CORE_DB}.INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = '${CORE_SCHEMA}' AND TABLE_NAME = 'PLAYER_RECOMMENDATIONS${LEGACY_SUFFIX}'
        AND COLUMN_NAME <> 'LINKED_CANONICAL_PLAYER_ID') a
FULL OUTER JOIN
     (SELECT ORDINAL_POSITION, COLUMN_NAME FROM ${CORE_DB}.INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = '${CORE_SCHEMA}' AND TABLE_NAME = 'V_COMPAT_PLAYER_RECOMMENDATIONS') b
  ON a.ORDINAL_POSITION = b.ORDINAL_POSITION
WHERE a.COLUMN_NAME IS DISTINCT FROM b.COLUMN_NAME;

SELECT 'recommendations: column TYPE differs (app applies TRY_CAST; types must match exactly)' AS CHECK_NAME,
       a.COLUMN_NAME, a.DATA_TYPE || '(' || COALESCE(a.CHARACTER_MAXIMUM_LENGTH::VARCHAR, a.NUMERIC_PRECISION::VARCHAR || ',' || a.NUMERIC_SCALE::VARCHAR, '') || ')' AS LEGACY_TYPE,
       b.DATA_TYPE || '(' || COALESCE(b.CHARACTER_MAXIMUM_LENGTH::VARCHAR, b.NUMERIC_PRECISION::VARCHAR || ',' || b.NUMERIC_SCALE::VARCHAR, '') || ')' AS VIEW_TYPE
FROM ${CORE_DB}.INFORMATION_SCHEMA.COLUMNS a
JOIN ${CORE_DB}.INFORMATION_SCHEMA.COLUMNS b
  ON b.COLUMN_NAME = a.COLUMN_NAME
WHERE a.TABLE_SCHEMA = '${CORE_SCHEMA}' AND a.TABLE_NAME = 'PLAYER_RECOMMENDATIONS${LEGACY_SUFFIX}'
  AND b.TABLE_SCHEMA = '${CORE_SCHEMA}' AND b.TABLE_NAME = 'V_COMPAT_PLAYER_RECOMMENDATIONS'
  AND (a.DATA_TYPE IS DISTINCT FROM b.DATA_TYPE
    OR a.CHARACTER_MAXIMUM_LENGTH IS DISTINCT FROM b.CHARACTER_MAXIMUM_LENGTH
    OR a.NUMERIC_PRECISION IS DISTINCT FROM b.NUMERIC_PRECISION
    OR a.NUMERIC_SCALE IS DISTINCT FROM b.NUMERIC_SCALE);

SELECT 'recommendations: legacy rows missing or different in the view' AS CHECK_NAME, COUNT(*) AS N
FROM (SELECT
    ID, AGENT_NAME, AGENCY, AGENT_EMAIL, AGENT_NUMBER, DATE, TRANSFERMARKT_LINK, AGREEMENT_TYPE,
    CONTRACT_EXPIRY, CONTRACT_OPTIONS, POTENTIAL_DEAL_TYPE, TRANSFER_FEE, CURRENT_WAGES, EXPECTED_WAGES,
    ADDITIONAL_INFO, PLAYER_NAME, SUBMITTED_BY_USER_ID, STATUS, STATUS_UPDATED_AT, STATUS_UPDATED_BY,
    INTERNAL_NOTES, UPDATED_AT, CREATED_AT, EXPECTED_WAGES_CURRENCY, EXPECTED_WAGES_AMOUNT,
    CURRENT_WAGES_CURRENCY, CURRENT_WAGES_AMOUNT, TRANSFER_FEE_CURRENCY, TRANSFER_FEE_AMOUNT,
    RECOMMENDED_POSITION, PLAYER_DATE_OF_BIRTH, AGENT_STATUS, AGENT_STATUS_UPDATED_AT, EXPECTED_WAGES_MAX,
    EXPECTED_WAGES_MIN, CURRENT_WAGES_MAX, CURRENT_WAGES_MIN, WAGE_BASIS, TRANSFER_FEE_MAX, TRANSFER_FEE_MIN,
    LINKED_UNIVERSAL_ID
      FROM ${CORE}.PLAYER_RECOMMENDATIONS${LEGACY_SUFFIX}
      EXCEPT
      SELECT * FROM ${CORE}.V_COMPAT_PLAYER_RECOMMENDATIONS)
HAVING COUNT(*) > 0;

SELECT 'recommendations: view rows missing or different in legacy' AS CHECK_NAME, COUNT(*) AS N
FROM (SELECT * FROM ${CORE}.V_COMPAT_PLAYER_RECOMMENDATIONS
      EXCEPT
      SELECT
    ID, AGENT_NAME, AGENCY, AGENT_EMAIL, AGENT_NUMBER, DATE, TRANSFERMARKT_LINK, AGREEMENT_TYPE,
    CONTRACT_EXPIRY, CONTRACT_OPTIONS, POTENTIAL_DEAL_TYPE, TRANSFER_FEE, CURRENT_WAGES, EXPECTED_WAGES,
    ADDITIONAL_INFO, PLAYER_NAME, SUBMITTED_BY_USER_ID, STATUS, STATUS_UPDATED_AT, STATUS_UPDATED_BY,
    INTERNAL_NOTES, UPDATED_AT, CREATED_AT, EXPECTED_WAGES_CURRENCY, EXPECTED_WAGES_AMOUNT,
    CURRENT_WAGES_CURRENCY, CURRENT_WAGES_AMOUNT, TRANSFER_FEE_CURRENCY, TRANSFER_FEE_AMOUNT,
    RECOMMENDED_POSITION, PLAYER_DATE_OF_BIRTH, AGENT_STATUS, AGENT_STATUS_UPDATED_AT, EXPECTED_WAGES_MAX,
    EXPECTED_WAGES_MIN, CURRENT_WAGES_MAX, CURRENT_WAGES_MIN, WAGE_BASIS, TRANSFER_FEE_MAX, TRANSFER_FEE_MIN,
    LINKED_UNIVERSAL_ID
      FROM ${CORE}.PLAYER_RECOMMENDATIONS${LEGACY_SUFFIX})
HAVING COUNT(*) > 0;
