-- BACKFILL SQUAD METADATA FOR INTERNAL MATCHES
-- Generated automatically - review before running!
-- ====================================================================================================================


-- Match 3601: Maidstone United vs Eastbourne Borough (2025-10-21)
UPDATE MATCHES
SET     HOMESQUADID = 869,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 549,
    HOMESQUADCOUNTRYNAME = 'England',
    HOMESQUADHEIMSPIELID = 17600,
    HOMESQUADWYSCOUTID = 1995,
    AWAYSQUADID = 875,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 549,
    AWAYSQUADCOUNTRYNAME = 'England',
    AWAYSQUADWYSCOUTID = 1773
WHERE CAFC_MATCH_ID = 3601 AND DATA_SOURCE = 'internal';


-- Match 4001: FC Stevenage vs Crystal Palace U21 (2025-10-21)
UPDATE MATCHES
SET     HOMESQUADID = 940,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 549,
    HOMESQUADCOUNTRYNAME = 'England',
    HOMESQUADSKILLCORNERID = 2817,
    HOMESQUADHEIMSPIELID = 1825,
    HOMESQUADWYSCOUTID = 1705,
    AWAYSQUADID = 3253,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 549,
    AWAYSQUADCOUNTRYNAME = 'England',
    AWAYSQUADSKILLCORNERID = 4609,
    AWAYSQUADHEIMSPIELID = 105805,
    AWAYSQUADWYSCOUTID = 22983
WHERE CAFC_MATCH_ID = 4001 AND DATA_SOURCE = 'internal';


-- Match 2801: Birmingham City U18 vs Reading U18 (2025-10-18)
UPDATE MATCHES
SET     HOMESQUADID = 3321,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 549,
    HOMESQUADCOUNTRYNAME = 'England',
    HOMESQUADHEIMSPIELID = 160435
WHERE CAFC_MATCH_ID = 2801 AND DATA_SOURCE = 'internal';


-- Match 3801: Peterborough United vs Aston Villa U21 (2025-09-30)
UPDATE MATCHES
SET     HOMESQUADID = 965,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 549,
    HOMESQUADCOUNTRYNAME = 'England',
    HOMESQUADSKILLCORNERID = 1869,
    HOMESQUADHEIMSPIELID = 1463,
    HOMESQUADWYSCOUTID = 1668,
    AWAYSQUADID = 1461,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 549,
    AWAYSQUADCOUNTRYNAME = 'England',
    AWAYSQUADSKILLCORNERID = 2458,
    AWAYSQUADHEIMSPIELID = 105780,
    AWAYSQUADWYSCOUTID = 22974
WHERE CAFC_MATCH_ID = 3801 AND DATA_SOURCE = 'internal';


-- Match 2601: Notts County vs Barnsley (2025-09-30)
UPDATE MATCHES
SET     HOMESQUADID = 896,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 549,
    HOMESQUADCOUNTRYNAME = 'England',
    HOMESQUADSKILLCORNERID = 1563,
    HOMESQUADHEIMSPIELID = 1392,
    HOMESQUADWYSCOUTID = 1677
WHERE CAFC_MATCH_ID = 2601 AND DATA_SOURCE = 'internal';


-- Match 3901: Kawasaki Frontale vs Kashiwa Reysol (2025-09-29)
UPDATE MATCHES
SET     HOMESQUADID = 2055,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 537,
    HOMESQUADCOUNTRYNAME = 'Japan',
    HOMESQUADSKILLCORNERID = 1469,
    HOMESQUADHEIMSPIELID = 1118,
    HOMESQUADWYSCOUTID = 12812,
    AWAYSQUADID = 2095,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 537,
    AWAYSQUADCOUNTRYNAME = 'Japan',
    AWAYSQUADSKILLCORNERID = 1466,
    AWAYSQUADHEIMSPIELID = 1115,
    AWAYSQUADWYSCOUTID = 12807
WHERE CAFC_MATCH_ID = 3901 AND DATA_SOURCE = 'internal';


-- Match 2501: Leeds United U21 vs Sporting CP B (2025-09-25)
UPDATE MATCHES
SET     HOMESQUADID = 3252,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 549,
    HOMESQUADCOUNTRYNAME = 'England',
    HOMESQUADSKILLCORNERID = 2859,
    HOMESQUADHEIMSPIELID = 160424,
    HOMESQUADWYSCOUTID = 26662
WHERE CAFC_MATCH_ID = 2501 AND DATA_SOURCE = 'internal';


-- Match 3701: Sanfrecce Hiroshima vs Shonan Bellmare (2025-09-07)
UPDATE MATCHES
SET     HOMESQUADID = 2054,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 537,
    HOMESQUADCOUNTRYNAME = 'Japan',
    HOMESQUADSKILLCORNERID = 1467,
    HOMESQUADHEIMSPIELID = 17668,
    HOMESQUADWYSCOUTID = 12810,
    AWAYSQUADID = 2078,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 537,
    AWAYSQUADCOUNTRYNAME = 'Japan',
    AWAYSQUADSKILLCORNERID = 1472,
    AWAYSQUADHEIMSPIELID = 20358,
    AWAYSQUADWYSCOUTID = 12822
WHERE CAFC_MATCH_ID = 3701 AND DATA_SOURCE = 'internal';


-- Match 3202: Livingston FC vs Hibernian FC (2025-08-17)
UPDATE MATCHES
SET     HOMESQUADID = 2819,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 559,
    HOMESQUADCOUNTRYNAME = 'Scotland',
    HOMESQUADSKILLCORNERID = 1477,
    HOMESQUADHEIMSPIELID = 1227,
    HOMESQUADWYSCOUTID = 8515,
    AWAYSQUADID = 1437,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 559,
    AWAYSQUADCOUNTRYNAME = 'Scotland',
    AWAYSQUADSKILLCORNERID = 245,
    AWAYSQUADHEIMSPIELID = 982,
    AWAYSQUADWYSCOUTID = 8514
WHERE CAFC_MATCH_ID = 3202 AND DATA_SOURCE = 'internal';


-- Match 3101: St. Mirren FC vs Heart of Midlothian FC (2025-08-16)
UPDATE MATCHES
SET     HOMESQUADID = 2818,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 559,
    HOMESQUADCOUNTRYNAME = 'Scotland',
    HOMESQUADSKILLCORNERID = 249,
    HOMESQUADHEIMSPIELID = 1803,
    HOMESQUADWYSCOUTID = 8526,
    AWAYSQUADID = 827,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 559,
    AWAYSQUADCOUNTRYNAME = 'Scotland',
    AWAYSQUADSKILLCORNERID = 242,
    AWAYSQUADHEIMSPIELID = 965,
    AWAYSQUADWYSCOUTID = 8510
WHERE CAFC_MATCH_ID = 3101 AND DATA_SOURCE = 'internal';


-- Match 3201: Glasgow Rangers vs Alloa Athletic FC (2025-08-16)
UPDATE MATCHES
SET     HOMESQUADID = 822,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 559,
    HOMESQUADCOUNTRYNAME = 'Scotland',
    HOMESQUADSKILLCORNERID = 241,
    HOMESQUADHEIMSPIELID = 893,
    HOMESQUADWYSCOUTID = 8509
WHERE CAFC_MATCH_ID = 3201 AND DATA_SOURCE = 'internal';


-- Match 3001: Celtic Glasgow vs Falkirk FC (2025-08-15)
UPDATE MATCHES
SET     HOMESQUADID = 255,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 559,
    HOMESQUADCOUNTRYNAME = 'Scotland',
    HOMESQUADSKILLCORNERID = 248,
    HOMESQUADHEIMSPIELID = 356,
    HOMESQUADWYSCOUTID = 8508,
    AWAYSQUADID = 9270,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 559,
    AWAYSQUADCOUNTRYNAME = 'Scotland',
    AWAYSQUADSKILLCORNERID = 240,
    AWAYSQUADHEIMSPIELID = 581
WHERE CAFC_MATCH_ID = 3001 AND DATA_SOURCE = 'internal';


-- Match 2901: Hibernian FC vs FK Partizan Belgrad (2025-08-14)
UPDATE MATCHES
SET     HOMESQUADID = 1437,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 559,
    HOMESQUADCOUNTRYNAME = 'Scotland',
    HOMESQUADSKILLCORNERID = 245,
    HOMESQUADHEIMSPIELID = 982,
    HOMESQUADWYSCOUTID = 8514,
    AWAYSQUADID = 1056,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 576,
    AWAYSQUADCOUNTRYNAME = 'Serbia',
    AWAYSQUADSKILLCORNERID = 561,
    AWAYSQUADHEIMSPIELID = 1460,
    AWAYSQUADWYSCOUTID = 17091
WHERE CAFC_MATCH_ID = 2901 AND DATA_SOURCE = 'internal';


-- Match 1801: Western United vs Sydney FC (2025-07-29)
UPDATE MATCHES
SET     AWAYSQUADID = 2037,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 369,
    AWAYSQUADCOUNTRYNAME = 'Australia',
    AWAYSQUADSKILLCORNERID = 869,
    AWAYSQUADHEIMSPIELID = 1882,
    AWAYSQUADWYSCOUTID = 8309
WHERE CAFC_MATCH_ID = 1801 AND DATA_SOURCE = 'internal';


-- Match 2401: Ilves Tampere vs AZ Alkmaar (2025-07-24)
UPDATE MATCHES
SET     HOMESQUADID = 2953,
    HOMESQUADTYPE = 'CLUB',
    HOMESQUADCOUNTRYID = 475,
    HOMESQUADCOUNTRYNAME = 'Finland',
    HOMESQUADHEIMSPIELID = 13681,
    HOMESQUADWYSCOUTID = 4854,
    AWAYSQUADID = 390,
    AWAYSQUADTYPE = 'CLUB',
    AWAYSQUADCOUNTRYID = 384,
    AWAYSQUADCOUNTRYNAME = 'Netherlands',
    AWAYSQUADSKILLCORNERID = 178,
    AWAYSQUADHEIMSPIELID = 181,
    AWAYSQUADWYSCOUTID = 10
WHERE CAFC_MATCH_ID = 2401 AND DATA_SOURCE = 'internal';

