"""
Generate a compat view and its parity check from the LIVE legacy table's real column types.

The compat view must reproduce the legacy table exactly: same columns, same order, same TYPES (the app applies
TRY_CAST to some columns, and Snowflake rejects TRY_CAST(NUMBER(18,0)) where the column is NUMBER(38,0)). Typing
those casts by hand is error-prone, so this reads INFORMATION_SCHEMA.COLUMNS of the legacy table (read-only) and
writes both files.

    python tools/gen_compat_sql.py            # regenerate every domain spec below
    python tools/gen_compat_sql.py intel      # just one

Each spec gives, per legacy column IN LEGACY ORDER, the SQL expression that rebuilds it from the normalized tables.
Output: migrations/normalization/<view_file> and migrations/normalization/parity/<parity_file>.
"""
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent / "migrations" / "normalization"
sys.path.insert(0, str(HERE))

LIVE = "CAFC_DB.CORE"


def live_types(table: str):
    """[(column, sql type)] in legacy order, from the live legacy table."""
    from run_normalization_migrations import connect

    conn = connect()
    cur = conn.cursor()
    try:
        db, schema = LIVE.split(".")
        cur.execute(
            f"""SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE
                FROM {db}.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '{schema}' AND TABLE_NAME = '{table}'
                ORDER BY ORDINAL_POSITION"""
        )
        out = []
        for name, data_type, char_len, precision, scale in cur.fetchall():
            if data_type == "TEXT":
                sql_type = "VARCHAR" if char_len in (None, 16777216) else f"VARCHAR({char_len})"
            elif data_type == "NUMBER":
                sql_type = f"NUMBER({precision},{scale})"
            else:
                sql_type = data_type
            out.append((name, sql_type))
        return out
    finally:
        cur.close()
        conn.close()


def render_view(spec, types):
    by_name = dict(types)
    missing = [c for c, _ in types if c not in spec["columns"]]
    extra = [c for c in spec["columns"] if c not in by_name]
    if missing or extra:
        raise SystemExit(f"{spec['legacy']}: spec out of step with the live table; missing={missing} extra={extra}")
    lines = [f"    CAST({spec['columns'][name]} AS {sql_type}) AS {name}" for name, sql_type in types]
    ctes = spec.get("ctes", "").strip()
    return (
        f"-- GENERATED by tools/gen_compat_sql.py from the live column types of CAFC_DB.CORE.{spec['legacy']}. Do not hand-edit.\n"
        f"{spec['header'].rstrip()}\n\n"
        f"CREATE OR REPLACE VIEW ${{CORE}}.{spec['view']} AS\n"
        + (f"{ctes}\n" if ctes else "")
        + "SELECT\n" + ",\n".join(lines) + "\n"
        + f"{spec['from'].rstrip()};\n"
    )


def render_parity(spec, types):
    names = [c for c, _ in types]
    legacy = f"${{CORE}}.{spec['legacy']}${{LEGACY_SUFFIX}}"
    view = f"${{CORE}}.{spec['view']}"
    cols = ", ".join(names)
    added = spec.get("legacy_added_columns", [])
    added_filter = (" AND COLUMN_NAME NOT IN (" + ", ".join(f"'{c}'" for c in added) + ")") if added else ""
    tag = spec["tag"]
    return f"""-- GENERATED by tools/gen_compat_sql.py. Do not hand-edit.
-- {tag}: the compat view must reproduce the legacy table EXACTLY. Zero rows from every statement = pass.
-- The legacy side lists the ORIGINAL columns by name: the expand migrations may append columns to the legacy table
-- ({', '.join(added) or 'none for this table'}) that the app never selects.
-- ${{LEGACY_SUFFIX}} is empty before the swap and '_LEGACY' after it.

SELECT '{tag}: row counts differ' AS CHECK_NAME, l.N AS LEGACY_ROWS, v.N AS VIEW_ROWS
FROM (SELECT COUNT(*) AS N FROM {legacy}) l, (SELECT COUNT(*) AS N FROM {view}) v
WHERE l.N <> v.N;

SELECT '{tag}: columns differ in name or order' AS CHECK_NAME, a.ORDINAL_POSITION, a.COLUMN_NAME AS LEGACY_COLUMN, b.COLUMN_NAME AS VIEW_COLUMN
FROM (SELECT ORDINAL_POSITION, COLUMN_NAME FROM ${{CORE_DB}}.INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = '${{CORE_SCHEMA}}' AND TABLE_NAME = '{spec['legacy']}${{LEGACY_SUFFIX}}'{added_filter}) a
FULL OUTER JOIN
     (SELECT ORDINAL_POSITION, COLUMN_NAME FROM ${{CORE_DB}}.INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_SCHEMA = '${{CORE_SCHEMA}}' AND TABLE_NAME = '{spec['view']}') b
  ON a.ORDINAL_POSITION = b.ORDINAL_POSITION
WHERE a.COLUMN_NAME IS DISTINCT FROM b.COLUMN_NAME;

SELECT '{tag}: column TYPE differs (the app applies TRY_CAST; types must match exactly)' AS CHECK_NAME, a.COLUMN_NAME,
       a.DATA_TYPE || '(' || COALESCE(a.CHARACTER_MAXIMUM_LENGTH::VARCHAR, a.NUMERIC_PRECISION::VARCHAR || ',' || a.NUMERIC_SCALE::VARCHAR, '') || ')' AS LEGACY_TYPE,
       b.DATA_TYPE || '(' || COALESCE(b.CHARACTER_MAXIMUM_LENGTH::VARCHAR, b.NUMERIC_PRECISION::VARCHAR || ',' || b.NUMERIC_SCALE::VARCHAR, '') || ')' AS VIEW_TYPE
FROM ${{CORE_DB}}.INFORMATION_SCHEMA.COLUMNS a
JOIN ${{CORE_DB}}.INFORMATION_SCHEMA.COLUMNS b ON b.COLUMN_NAME = a.COLUMN_NAME
WHERE a.TABLE_SCHEMA = '${{CORE_SCHEMA}}' AND a.TABLE_NAME = '{spec['legacy']}${{LEGACY_SUFFIX}}'
  AND b.TABLE_SCHEMA = '${{CORE_SCHEMA}}' AND b.TABLE_NAME = '{spec['view']}'
  AND (a.DATA_TYPE IS DISTINCT FROM b.DATA_TYPE
    OR a.CHARACTER_MAXIMUM_LENGTH IS DISTINCT FROM b.CHARACTER_MAXIMUM_LENGTH
    OR a.NUMERIC_PRECISION IS DISTINCT FROM b.NUMERIC_PRECISION
    OR a.NUMERIC_SCALE IS DISTINCT FROM b.NUMERIC_SCALE);

SELECT '{tag}: legacy rows missing or different in the view' AS CHECK_NAME, COUNT(*) AS N
FROM (SELECT {cols}
      FROM {legacy}
      EXCEPT
      SELECT * FROM {view})
HAVING COUNT(*) > 0;

SELECT '{tag}: view rows missing or different in legacy' AS CHECK_NAME, COUNT(*) AS N
FROM (SELECT * FROM {view}
      EXCEPT
      SELECT {cols}
      FROM {legacy})
HAVING COUNT(*) > 0;
"""


def main(names):
    from specs import SPECS  # domain specs live beside this file

    for name in names or list(SPECS):
        spec = SPECS[name]
        types = live_types(spec["legacy"])
        (ROOT / spec["view_file"]).write_text(render_view(spec, types))
        (ROOT / "parity" / spec["parity_file"]).write_text(render_parity(spec, types))
        print(f"{name}: wrote {spec['view_file']} and parity/{spec['parity_file']} ({len(types)} columns)")


if __name__ == "__main__":
    main(sys.argv[1:])
