ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS PLAYER_NAME VARCHAR(255);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS SUBMITTED_BY_USER_ID INTEGER;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS STATUS VARCHAR(32);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS STATUS_UPDATED_AT TIMESTAMP;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS STATUS_UPDATED_BY INTEGER;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS INTERNAL_NOTES VARCHAR(5000);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS TRANSFER_FEE_AMOUNT NUMBER(18,0);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS TRANSFER_FEE_CURRENCY VARCHAR(3);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS CURRENT_WAGES_AMOUNT NUMBER(18,0);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS CURRENT_WAGES_CURRENCY VARCHAR(3);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS EXPECTED_WAGES_AMOUNT NUMBER(18,0);
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS EXPECTED_WAGES_CURRENCY VARCHAR(3);

CREATE TABLE IF NOT EXISTS AGENT_PROFILES (
  USER_ID INTEGER PRIMARY KEY,
  AGENT_NAME VARCHAR(255),
  AGENCY VARCHAR(255),
  AGENT_EMAIL VARCHAR(255),
  AGENT_NUMBER VARCHAR(100),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STATUS_HISTORY (
  ID INTEGER AUTOINCREMENT,
  RECOMMENDATION_ID INTEGER NOT NULL,
  OLD_STATUS VARCHAR(32),
  NEW_STATUS VARCHAR(32) NOT NULL,
  CHANGED_BY INTEGER,
  CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

UPDATE PLAYER_RECOMMENDATIONS
SET
  STATUS = COALESCE(STATUS, 'Submitted'),
  CREATED_AT = COALESCE(CREATED_AT, CURRENT_TIMESTAMP()),
  UPDATED_AT = COALESCE(UPDATED_AT, CURRENT_TIMESTAMP()),
  STATUS_UPDATED_AT = COALESCE(STATUS_UPDATED_AT, CURRENT_TIMESTAMP());
