-- Adds columns needed for the "reference_form" Intel Form subtype.
-- All Intel Form subtypes share PLAYER_INFORMATION; INTEL_TYPE discriminates them.
-- Reference Form reuses CONTACT_NAME, CONTACT_ORGANISATION, DATE_OF_INFORMATION
-- and CONVERSATION_NOTES (for the "Reference" textarea body).
-- The four columns below are subtype-specific.

ALTER TABLE PLAYER_INFORMATION ADD COLUMN IF NOT EXISTS RELATIONSHIP_TO_PLAYER VARCHAR;
ALTER TABLE PLAYER_INFORMATION ADD COLUMN IF NOT EXISTS LENGTH_OF_RELATIONSHIP VARCHAR;
ALTER TABLE PLAYER_INFORMATION ADD COLUMN IF NOT EXISTS RELEVANCE_OF_RELATIONSHIP VARCHAR;
ALTER TABLE PLAYER_INFORMATION ADD COLUMN IF NOT EXISTS REFERENCE_RATING VARCHAR;
