-- Add RECOMMENDED_POSITION column if it doesn't exist
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS RECOMMENDED_POSITION VARCHAR(500);

-- Add PLAYER_DATE_OF_BIRTH column if it doesn't exist
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS PLAYER_DATE_OF_BIRTH DATE;

-- Add AGENT_STATUS column for agent-side status management (separate from internal STATUS)
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS AGENT_STATUS VARCHAR(100) DEFAULT 'Active';

-- Add AGENT_STATUS_UPDATED_AT column to track when agent changed their status
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS AGENT_STATUS_UPDATED_AT TIMESTAMP;

-- Add min/max wage columns to support wage banding (e.g., 12000-20000)
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS CURRENT_WAGES_MIN INTEGER;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS CURRENT_WAGES_MAX INTEGER;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS EXPECTED_WAGES_MIN INTEGER;
ALTER TABLE PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS EXPECTED_WAGES_MAX INTEGER;