-- 000_snapshot.sql
-- Rollback point: zero-copy clones of every table the normalization touches.
-- IF NOT EXISTS on purpose: a re-run must never overwrite the first snapshot.
-- Restore one table:  CREATE OR REPLACE TABLE ${CORE}.<T> CLONE ${SNAPSHOT}.<T>;

CREATE SCHEMA IF NOT EXISTS ${SNAPSHOT};

CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.USERS                          CLONE ${CORE}.USERS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.SCOUT_REPORTS                  CLONE ${CORE}.SCOUT_REPORTS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.SCOUT_REPORT_ATTRIBUTE_SCORES  CLONE ${CORE}.SCOUT_REPORT_ATTRIBUTE_SCORES;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.PLAYER_LISTS                   CLONE ${CORE}.PLAYER_LISTS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.PLAYER_LIST_ITEMS              CLONE ${CORE}.PLAYER_LIST_ITEMS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.PLAYER_LIST_FLAGS              CLONE ${CORE}.PLAYER_LIST_FLAGS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.PLAYER_STAGE_HISTORY           CLONE ${CORE}.PLAYER_STAGE_HISTORY;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.SHARED_REPORT_LINKS            CLONE ${CORE}.SHARED_REPORT_LINKS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.PLAYER_INFORMATION             CLONE ${CORE}.PLAYER_INFORMATION;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.PLAYER_RECOMMENDATIONS         CLONE ${CORE}.PLAYER_RECOMMENDATIONS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.AGENT_PROFILES                 CLONE ${CORE}.AGENT_PROFILES;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.SCOUT_REPORT_VIEWS             CLONE ${CORE}.SCOUT_REPORT_VIEWS;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.STATUS_HISTORY                 CLONE ${CORE}.STATUS_HISTORY;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.RECOMMENDATION_NOTES_HISTORY   CLONE ${CORE}.RECOMMENDATION_NOTES_HISTORY;
CREATE TABLE IF NOT EXISTS ${SNAPSHOT}.PLAYER_NOTES                   CLONE ${CORE}.PLAYER_NOTES;
