-- 010_lookups.sql
-- Lookup tables. Seeded from the code constants in backend/main.py (ORIGIN='CODE',
-- active) UNION every distinct value already present in the data (ORIGIN='DATA',
-- INACTIVE until a human decides to keep, fix or retire it). ROLES is seeded from
-- code only: a role is an authorization decision, never inferred from data.
-- PK/UNIQUE are informational in Snowflake; validate/ enforces them.

-- ---- ROLES ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.ROLES (
    ROLE_CODE         VARCHAR(50)  NOT NULL,
    DISPLAY_NAME      VARCHAR(100) NOT NULL,
    IS_INTERNAL       BOOLEAN      NOT NULL,
    SEES_ALL_REPORTS  BOOLEAN      NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_CODE)
);

MERGE INTO ${CORE}.ROLES t
USING (
    SELECT * FROM VALUES
        ('admin',          'Admin',          TRUE,  TRUE),
        ('senior_manager', 'Senior Manager', TRUE,  TRUE),
        ('manager',        'Manager',        TRUE,  TRUE),
        ('loan_manager',   'Loan Manager',   TRUE,  FALSE),
        ('scout',          'Scout',          TRUE,  FALSE),
        ('agent',          'Agent',          FALSE, FALSE),
        ('intel_reviewer', 'Intel Reviewer', FALSE, FALSE)
        AS v(ROLE_CODE, DISPLAY_NAME, IS_INTERNAL, SEES_ALL_REPORTS)
) s ON t.ROLE_CODE = s.ROLE_CODE
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, DISPLAY_NAME, IS_INTERNAL, SEES_ALL_REPORTS)
    VALUES (s.ROLE_CODE, s.DISPLAY_NAME, s.IS_INTERNAL, s.SEES_ALL_REPORTS);

-- ---- Generic code lookups: REPORT_TYPES -------------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.REPORT_TYPES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_REPORT_TYPES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.REPORT_TYPES t
USING (
    SELECT CODE, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, 'CODE' AS ORIGIN FROM VALUES ('Player Assessment'), ('Flag'), ('Clips')
        UNION ALL
        SELECT DISTINCT TRIM(REPORT_TYPE), 'DATA' FROM ${CORE}.SCOUT_REPORTS WHERE TRIM(REPORT_TYPE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, NULL, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- REPORT_PURPOSES ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.REPORT_PURPOSES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_REPORT_PURPOSES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.REPORT_PURPOSES t
USING (
    SELECT CODE, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, 'CODE' AS ORIGIN FROM VALUES
            ('Player Report'), ('Loan Report'), ('Player Assessment'), ('Loan Assessment')
        UNION ALL
        SELECT DISTINCT TRIM(PURPOSE), 'DATA' FROM ${CORE}.SCOUT_REPORTS WHERE TRIM(PURPOSE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, NULL, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- SCOUTING_TYPES ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.SCOUTING_TYPES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_SCOUTING_TYPES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.SCOUTING_TYPES t
USING (
    SELECT CODE, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, 'CODE' AS ORIGIN FROM VALUES ('Live'), ('Video')
        UNION ALL
        SELECT DISTINCT TRIM(SCOUTING_TYPE), 'DATA' FROM ${CORE}.SCOUT_REPORTS WHERE TRIM(SCOUTING_TYPE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, NULL, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- FLAG_CATEGORIES / CLIP_CATEGORIES ---------------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.FLAG_CATEGORIES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_FLAG_CATEGORIES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.FLAG_CATEGORIES t
USING (
    SELECT CODE, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, 'CODE' AS ORIGIN FROM VALUES ('Monitor'), ('No Action'), ('Target'), ('Scout'), ('Neutral'), ('Positive'), ('Negative'),
            ('Future Scouting'), ('Outstanding/Above Level')
        UNION ALL
        SELECT DISTINCT TRIM(FLAG_CATEGORY), 'DATA' FROM ${CORE}.SCOUT_REPORTS WHERE TRIM(FLAG_CATEGORY) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, NULL, s.ORIGIN = 'CODE', s.ORIGIN);

CREATE TABLE IF NOT EXISTS ${CORE}.CLIP_CATEGORIES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CLIP_CATEGORIES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.CLIP_CATEGORIES t
USING (
    SELECT CODE, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, 'CODE' AS ORIGIN FROM VALUES ('Positive'), ('Neutral'), ('Negative')
        UNION ALL
        SELECT DISTINCT TRIM(CLIP_CATEGORY), 'DATA' FROM ${CORE}.SCOUT_REPORTS WHERE TRIM(CLIP_CATEGORY) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, NULL, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- LIST_CATEGORIES ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.LIST_CATEGORIES (
    CODE VARCHAR(50) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_LIST_CATEGORIES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.LIST_CATEGORIES t
USING (
    SELECT CODE, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, 'CODE' AS ORIGIN FROM VALUES ('first_team'), ('emerging_talent_u21'), ('emerging_talent_u18')
        UNION ALL
        SELECT DISTINCT TRIM(LIST_CATEGORY), 'DATA' FROM ${CORE}.PLAYER_LISTS WHERE TRIM(LIST_CATEGORY) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, NULL, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- LIST_STAGES (has dependent attributes: order + terminal flag) -----------
CREATE TABLE IF NOT EXISTS ${CORE}.LIST_STAGES (
    CODE        VARCHAR(50) NOT NULL,
    SORT_ORDER  NUMBER(5,0) NOT NULL,
    IS_TERMINAL BOOLEAN     NOT NULL,
    IS_ACTIVE   BOOLEAN     NOT NULL,
    ORIGIN      VARCHAR(10) NOT NULL,
    CONSTRAINT PK_LIST_STAGES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.LIST_STAGES t
USING (
    SELECT CODE, MIN(SORT_ORDER) AS SORT_ORDER, BOOLOR_AGG(IS_TERMINAL) AS IS_TERMINAL, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, column2 AS SORT_ORDER, column3 AS IS_TERMINAL, 'CODE' AS ORIGIN
        FROM VALUES ('Stage 1', 1, FALSE), ('Stage 2', 2, FALSE), ('Stage 3', 3, FALSE), ('Stage 4', 4, FALSE), ('Archived', 5, TRUE)
        UNION ALL
        SELECT DISTINCT TRIM(STAGE), 99, FALSE, 'DATA' FROM ${CORE}.PLAYER_LIST_ITEMS WHERE TRIM(STAGE) <> ''
        UNION ALL
        SELECT DISTINCT TRIM(NEW_STAGE), 99, FALSE, 'DATA' FROM ${CORE}.PLAYER_STAGE_HISTORY WHERE TRIM(NEW_STAGE) <> ''
        UNION ALL
        SELECT DISTINCT TRIM(OLD_STAGE), 99, FALSE, 'DATA' FROM ${CORE}.PLAYER_STAGE_HISTORY WHERE TRIM(OLD_STAGE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_TERMINAL, IS_ACTIVE, ORIGIN)
    VALUES (s.CODE, s.SORT_ORDER, s.IS_TERMINAL, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- RECOMMENDATION_STATUSES / AGENT_STATUSES --------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.RECOMMENDATION_STATUSES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_RECOMMENDATION_STATUSES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.RECOMMENDATION_STATUSES t
USING (
    SELECT CODE, MIN(SORT_ORDER) AS SORT_ORDER, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, column2 AS SORT_ORDER, 'CODE' AS ORIGIN FROM VALUES
            ('Submitted', 1), ('Under Review', 2),
            ('Added / Already in First Team Scouting Process', 3),
            ('Added / Already in Emerging Talent Process', 4),
            ('Not Currently under Consideration', 5)
        UNION ALL SELECT DISTINCT TRIM(STATUS), 99, 'DATA' FROM ${CORE}.PLAYER_RECOMMENDATIONS WHERE TRIM(STATUS) <> ''
        UNION ALL SELECT DISTINCT TRIM(NEW_STATUS), 99, 'DATA' FROM ${CORE}.STATUS_HISTORY WHERE TRIM(NEW_STATUS) <> ''
        UNION ALL SELECT DISTINCT TRIM(OLD_STATUS), 99, 'DATA' FROM ${CORE}.STATUS_HISTORY WHERE TRIM(OLD_STATUS) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, s.SORT_ORDER, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- INTEL_TYPES --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_TYPES (
    CODE VARCHAR(50) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_INTEL_TYPES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.INTEL_TYPES t
USING (
    SELECT CODE, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, 'CODE' AS ORIGIN FROM VALUES ('player_information'), ('general_note'), ('reference_form')
        UNION ALL
        SELECT DISTINCT TRIM(INTEL_TYPE), 'DATA' FROM ${CORE}.PLAYER_INFORMATION WHERE TRIM(INTEL_TYPE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, NULL, s.ORIGIN = 'CODE', s.ORIGIN);

-- ---- DEAL_TYPES / RELATIONSHIP_TYPES (multi-valued today: comma-joined) ------
-- Intel stores deal types as lowercase codes (permanent, free, loan, loan_with_option, na);
-- recommendations store the display labels. One vocabulary: the labels. 'na' means "not
-- applicable" and produces no row. Unknown values pass through trimmed (-> ORIGIN='DATA', inactive).
CREATE OR REPLACE FUNCTION ${CORE}.CANONICAL_DEAL_TYPE(v VARCHAR)
RETURNS VARCHAR
AS $$
    CASE LOWER(TRIM(v))
        WHEN 'permanent'        THEN 'Permanent Transfer'
        WHEN 'free'             THEN 'Free'
        WHEN 'loan'             THEN 'Loan'
        WHEN 'loan_with_option' THEN 'Loan with Option'
        WHEN 'na'               THEN NULL
        WHEN ''                 THEN NULL
        ELSE TRIM(v)
    END
$$;

CREATE TABLE IF NOT EXISTS ${CORE}.DEAL_TYPES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_DEAL_TYPES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.DEAL_TYPES t
USING (
    SELECT CODE, MIN(SORT_ORDER) AS SORT_ORDER, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, column2 AS SORT_ORDER, 'CODE' AS ORIGIN FROM VALUES
            ('Free', 1), ('Permanent Transfer', 2), ('Loan', 3), ('Loan with Option', 4)
        UNION ALL
        SELECT DISTINCT ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE), 99, 'DATA'
        FROM ${CORE}.PLAYER_RECOMMENDATIONS r, LATERAL SPLIT_TO_TABLE(r.POTENTIAL_DEAL_TYPE, ',') s
        WHERE ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE) IS NOT NULL
        UNION ALL
        SELECT DISTINCT ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE), 99, 'DATA'
        FROM ${CORE}.PLAYER_INFORMATION i, LATERAL SPLIT_TO_TABLE(i.POTENTIAL_DEAL_TYPE, ',') s
        WHERE ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE) IS NOT NULL
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, s.SORT_ORDER, s.ORIGIN = 'CODE', s.ORIGIN);

CREATE TABLE IF NOT EXISTS ${CORE}.RELATIONSHIP_TYPES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_RELATIONSHIP_TYPES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.RELATIONSHIP_TYPES t
USING (
    SELECT CODE, MIN(SORT_ORDER) AS SORT_ORDER, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, column2 AS SORT_ORDER, 'CODE' AS ORIGIN FROM VALUES
            ('Managed/Coached', 1), ('Worked With', 2), ('Played With', 3),
            ('Friend/Family', 4), ('Mutual Circles', 5), ('Other', 6)
        UNION ALL
        SELECT DISTINCT TRIM(s.VALUE), 99, 'DATA'
        FROM ${CORE}.PLAYER_INFORMATION i, LATERAL SPLIT_TO_TABLE(i.RELATIONSHIP_TO_PLAYER, ',') s
        WHERE TRIM(s.VALUE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, s.SORT_ORDER, s.ORIGIN = 'CODE', s.ORIGIN);

-- USERS.ROLE, SCOUT_REPORTS.REPORT_TYPE etc. keep their names and types, so no app
-- change is needed. References from legacy tables to these lookups are enforced by
-- validate/010_lookups.sql, not by declared FKs: Snowflake only accepts an FK to a
-- declared PK/UNIQUE, which the cloned legacy tables may not have.

-- ---- Multi-valued recommendation columns (comma-joined today; see 040) --------------------
-- Live data 2026-09-30: RECOMMENDED_POSITION is comma-joined on 270 of 596 rows, AGREEMENT_TYPE on 17,
-- CONTRACT_OPTIONS on 13. AGREEMENT_TYPE also holds two legacy values that are no longer in the UI or
-- ALLOWED_AGREEMENT_TYPES ('Player Agreement/Mandate' on 136 uses, 'Club Mandate' on 1); they seed as
-- ORIGIN='DATA' (inactive) so a human decides whether to keep or remap them.
CREATE TABLE IF NOT EXISTS ${CORE}.AGREEMENT_TYPES (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_AGREEMENT_TYPES PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.AGREEMENT_TYPES t
USING (
    SELECT CODE, MIN(SORT_ORDER) AS SORT_ORDER, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, column2 AS SORT_ORDER, 'CODE' AS ORIGIN FROM VALUES
            ('Exclusive/Registered Player Agreement', 1), ('Mandate (Player)', 2), ('Mandate (Selling Club)', 3), ('None', 4)
        UNION ALL
        SELECT DISTINCT TRIM(s.VALUE), 99, 'DATA'
        FROM ${CORE}.PLAYER_RECOMMENDATIONS r, LATERAL SPLIT_TO_TABLE(r.AGREEMENT_TYPE, ',') s
        WHERE TRIM(s.VALUE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, s.SORT_ORDER, s.ORIGIN = 'CODE', s.ORIGIN);

CREATE TABLE IF NOT EXISTS ${CORE}.CONTRACT_OPTIONS (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_CONTRACT_OPTIONS PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.CONTRACT_OPTIONS t
USING (
    SELECT CODE, MIN(SORT_ORDER) AS SORT_ORDER, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, column2 AS SORT_ORDER, 'CODE' AS ORIGIN FROM VALUES
            ('None', 1), ('+1 Club', 2), ('+1 Player', 3), ('+1 Mutual', 4), ('+2 Club', 5), ('+2 Player', 6), ('+2 Mutual', 7), ('Other', 8)
        UNION ALL
        SELECT DISTINCT TRIM(s.VALUE), 99, 'DATA'
        FROM ${CORE}.PLAYER_RECOMMENDATIONS r, LATERAL SPLIT_TO_TABLE(r.CONTRACT_OPTIONS, ',') s
        WHERE TRIM(s.VALUE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, s.SORT_ORDER, s.ORIGIN = 'CODE', s.ORIGIN);

CREATE TABLE IF NOT EXISTS ${CORE}.RECOMMENDED_POSITIONS (
    CODE VARCHAR(100) NOT NULL, SORT_ORDER NUMBER(5,0), IS_ACTIVE BOOLEAN NOT NULL, ORIGIN VARCHAR(10) NOT NULL,
    CONSTRAINT PK_RECOMMENDED_POSITIONS PRIMARY KEY (CODE)
);
MERGE INTO ${CORE}.RECOMMENDED_POSITIONS t
USING (
    SELECT CODE, MIN(SORT_ORDER) AS SORT_ORDER, MIN(ORIGIN) AS ORIGIN FROM (
        SELECT column1 AS CODE, column2 AS SORT_ORDER, 'CODE' AS ORIGIN FROM VALUES
            ('GK', 1), ('RB', 2), ('RWB', 3), ('RCB(3)', 4), ('RCB(2)', 5), ('CCB(3)', 6), ('LCB(2)', 7), ('LCB(3)', 8),
            ('LWB', 9), ('LB', 10), ('DM', 11), ('CM', 12), ('RAM', 13), ('AM', 14), ('LAM', 15), ('RW', 16), ('LW', 17),
            ('Target Man CF', 18), ('In Behind CF', 19)
        UNION ALL
        SELECT DISTINCT TRIM(s.VALUE), 99, 'DATA'
        FROM ${CORE}.PLAYER_RECOMMENDATIONS r, LATERAL SPLIT_TO_TABLE(r.RECOMMENDED_POSITION, ',') s
        WHERE TRIM(s.VALUE) <> ''
    ) GROUP BY CODE
) s ON t.CODE = s.CODE
WHEN NOT MATCHED THEN INSERT (CODE, SORT_ORDER, IS_ACTIVE, ORIGIN) VALUES (s.CODE, s.SORT_ORDER, s.ORIGIN = 'CODE', s.ORIGIN);
