-- @sync-until-cutover: reports_lists
-- 020_keys_reports_lists.sql
-- One canonical key per entity reference for scout reports, list items and list flags,
-- added ALONGSIDE the legacy dual columns.
--
--   players : the row's CAFC_PLAYER_ID if that player exists, else resolve('IMPECT', PLAYER_ID)
--             (CORE_PLAYER_ID_RESOLUTIONS honours identity overrides = the platform's merges)
--   fixtures: resolve('IMPECT', MATCH_ID), else CAFC_FIXTURE_ID for fixtures with no IMPECT
--             identity. MATCH_ID is overloaded; when it matches BOTH interpretations the key is
--             left NULL and reported (never guessed). Live data today: 0 such rows.
--
-- FULL RECOMPUTE, not fill-the-NULLs: until this domain cuts over, the legacy columns remain the
-- source of truth and the app rewrites them in place (/admin/merge-players,
-- /admin/merge-duplicate-match, the platform's remap scripts) and identity overrides change what
-- IMPECT ids resolve to. The expected keys live in views so this sync and the validation share
-- one definition. After `--mark-cutover reports_lists` the runner refuses this file.

ALTER TABLE ${CORE}.SCOUT_REPORTS     ADD COLUMN IF NOT EXISTS CANONICAL_PLAYER_ID  NUMBER(38,0);
ALTER TABLE ${CORE}.SCOUT_REPORTS     ADD COLUMN IF NOT EXISTS CANONICAL_FIXTURE_ID NUMBER(38,0);
ALTER TABLE ${CORE}.PLAYER_LIST_ITEMS ADD COLUMN IF NOT EXISTS CANONICAL_PLAYER_ID  NUMBER(38,0);
ALTER TABLE ${CORE}.PLAYER_LIST_FLAGS ADD COLUMN IF NOT EXISTS CAFC_PLAYER_ID       NUMBER(38,0);

CREATE OR REPLACE VIEW ${CORE}.V_SCOUT_REPORT_KEYS AS
SELECT s.ID,
       COALESCE(p.CAFC_PLAYER_ID, r.CAFC_PLAYER_ID) AS EXPECTED_PLAYER_ID,
       CASE WHEN f.CAFC_FIXTURE_ID IS NOT NULL AND m.CAFC_FIXTURE_ID IS NOT NULL THEN NULL
            ELSE COALESCE(f.CAFC_FIXTURE_ID, m.CAFC_FIXTURE_ID) END AS EXPECTED_FIXTURE_ID
FROM ${CORE}.SCOUT_REPORTS s
LEFT JOIN ${CORE}.PLAYERS p ON p.CAFC_PLAYER_ID = s.CAFC_PLAYER_ID
LEFT JOIN ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
       ON r.SOURCE_SYSTEM = 'IMPECT' AND r.SOURCE_PLAYER_ID = TO_VARCHAR(s.PLAYER_ID)
LEFT JOIN ${CORE}.CORE_FIXTURE_ID_RESOLUTIONS f
       ON f.SOURCE_SYSTEM = 'IMPECT' AND f.SOURCE_FIXTURE_ID = TO_VARCHAR(s.MATCH_ID)
LEFT JOIN (SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURES
           WHERE CAFC_FIXTURE_ID NOT IN (SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
                                         WHERE SOURCE_SYSTEM = 'IMPECT' AND CAFC_FIXTURE_ID IS NOT NULL)) m
       ON m.CAFC_FIXTURE_ID = s.MATCH_ID;

CREATE OR REPLACE VIEW ${CORE}.V_PLAYER_LIST_ITEM_KEYS AS
SELECT s.ID, COALESCE(p.CAFC_PLAYER_ID, r.CAFC_PLAYER_ID) AS EXPECTED_PLAYER_ID
FROM ${CORE}.PLAYER_LIST_ITEMS s
LEFT JOIN ${CORE}.PLAYERS p ON p.CAFC_PLAYER_ID = s.CAFC_PLAYER_ID
LEFT JOIN ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
       ON r.SOURCE_SYSTEM = 'IMPECT' AND r.SOURCE_PLAYER_ID = TO_VARCHAR(s.PLAYER_ID);

-- UNIVERSAL_ID is 'internal_<CAFC id>' or 'external_<IMPECT id>'.
CREATE OR REPLACE VIEW ${CORE}.V_PLAYER_LIST_FLAG_KEYS AS
SELECT s.UNIVERSAL_ID,
       CASE WHEN REGEXP_LIKE(s.UNIVERSAL_ID, '^internal_[0-9]+$') THEN p.CAFC_PLAYER_ID
            WHEN REGEXP_LIKE(s.UNIVERSAL_ID, '^external_[0-9]+$') THEN r.CAFC_PLAYER_ID END AS EXPECTED_PLAYER_ID
FROM ${CORE}.PLAYER_LIST_FLAGS s
LEFT JOIN ${CORE}.PLAYERS p
       ON p.CAFC_PLAYER_ID = TRY_TO_NUMBER(REGEXP_SUBSTR(s.UNIVERSAL_ID, '^internal_([0-9]+)$', 1, 1, 'e', 1))
LEFT JOIN ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
       ON r.SOURCE_SYSTEM = 'IMPECT' AND r.SOURCE_PLAYER_ID = REGEXP_SUBSTR(s.UNIVERSAL_ID, '^external_([0-9]+)$', 1, 1, 'e', 1);

UPDATE ${CORE}.SCOUT_REPORTS t
SET CANONICAL_PLAYER_ID = k.EXPECTED_PLAYER_ID, CANONICAL_FIXTURE_ID = k.EXPECTED_FIXTURE_ID
FROM ${CORE}.V_SCOUT_REPORT_KEYS k
WHERE t.ID = k.ID
  AND (t.CANONICAL_PLAYER_ID  IS DISTINCT FROM k.EXPECTED_PLAYER_ID
    OR t.CANONICAL_FIXTURE_ID IS DISTINCT FROM k.EXPECTED_FIXTURE_ID);

UPDATE ${CORE}.PLAYER_LIST_ITEMS t
SET CANONICAL_PLAYER_ID = k.EXPECTED_PLAYER_ID
FROM ${CORE}.V_PLAYER_LIST_ITEM_KEYS k
WHERE t.ID = k.ID AND t.CANONICAL_PLAYER_ID IS DISTINCT FROM k.EXPECTED_PLAYER_ID;

UPDATE ${CORE}.PLAYER_LIST_FLAGS t
SET CAFC_PLAYER_ID = k.EXPECTED_PLAYER_ID
FROM ${CORE}.V_PLAYER_LIST_FLAG_KEYS k
WHERE t.UNIVERSAL_ID = k.UNIVERSAL_ID AND t.CAFC_PLAYER_ID IS DISTINCT FROM k.EXPECTED_PLAYER_ID;
