-- 020_canonical_keys.sql
-- One canonical key per entity reference, added ALONGSIDE the legacy dual columns.
--
--   players : COALESCE(CAFC_PLAYER_ID, resolve('IMPECT', PLAYER_ID))
--   fixtures: resolve('IMPECT', MATCH_ID), else CAFC_FIXTURE_ID for fixtures with
--             no IMPECT identity (MATCH_ID is overloaded: IMPECT id for external
--             fixtures, CAFC_MATCH_ID for manual ones)
--
-- Re-runnable: every UPDATE only fills rows that are still NULL, so re-running
-- before app cutover picks up rows written by the legacy code path.
-- Rows that cannot be resolved, or whose MATCH_ID is ambiguous, stay NULL and
-- are reported by validate/020_canonical_keys.sql; nothing is guessed.

-- ---- SCOUT_REPORTS ------------------------------------------------------------
ALTER TABLE ${CORE}.SCOUT_REPORTS ADD COLUMN IF NOT EXISTS CANONICAL_PLAYER_ID  NUMBER(38,0);
ALTER TABLE ${CORE}.SCOUT_REPORTS ADD COLUMN IF NOT EXISTS CANONICAL_FIXTURE_ID NUMBER(38,0);

UPDATE ${CORE}.SCOUT_REPORTS
SET CANONICAL_PLAYER_ID = CAFC_PLAYER_ID
WHERE CANONICAL_PLAYER_ID IS NULL AND CAFC_PLAYER_ID IS NOT NULL
  AND CAFC_PLAYER_ID IN (SELECT CAFC_PLAYER_ID FROM ${CORE}.PLAYERS);

UPDATE ${CORE}.SCOUT_REPORTS sr
SET CANONICAL_PLAYER_ID = r.CAFC_PLAYER_ID
FROM ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
WHERE sr.CANONICAL_PLAYER_ID IS NULL
  AND sr.PLAYER_ID IS NOT NULL
  AND r.SOURCE_SYSTEM = 'IMPECT'
  AND r.SOURCE_PLAYER_ID = TO_VARCHAR(sr.PLAYER_ID);

UPDATE ${CORE}.SCOUT_REPORTS sr
SET CANONICAL_FIXTURE_ID = f.CAFC_FIXTURE_ID
FROM ${CORE}.CORE_FIXTURE_ID_RESOLUTIONS f
WHERE sr.CANONICAL_FIXTURE_ID IS NULL
  AND sr.MATCH_ID IS NOT NULL
  AND f.SOURCE_SYSTEM = 'IMPECT'
  AND f.SOURCE_FIXTURE_ID = TO_VARCHAR(sr.MATCH_ID)
  AND sr.MATCH_ID NOT IN (
      SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURES
      WHERE CAFC_FIXTURE_ID NOT IN (
          SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
          WHERE SOURCE_SYSTEM = 'IMPECT' AND CAFC_FIXTURE_ID IS NOT NULL));

UPDATE ${CORE}.SCOUT_REPORTS sr
SET CANONICAL_FIXTURE_ID = fx.CAFC_FIXTURE_ID
FROM ${CORE}.FIXTURES fx
WHERE sr.CANONICAL_FIXTURE_ID IS NULL
  AND sr.MATCH_ID IS NOT NULL
  AND sr.MATCH_ID = fx.CAFC_FIXTURE_ID
  AND fx.CAFC_FIXTURE_ID NOT IN (
      SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
      WHERE SOURCE_SYSTEM = 'IMPECT' AND CAFC_FIXTURE_ID IS NOT NULL)
  AND TO_VARCHAR(sr.MATCH_ID) NOT IN (
      SELECT SOURCE_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
      WHERE SOURCE_SYSTEM = 'IMPECT' AND SOURCE_FIXTURE_ID IS NOT NULL);

-- ---- PLAYER_LIST_ITEMS -----------------------------------------------------------
ALTER TABLE ${CORE}.PLAYER_LIST_ITEMS ADD COLUMN IF NOT EXISTS CANONICAL_PLAYER_ID NUMBER(38,0);

UPDATE ${CORE}.PLAYER_LIST_ITEMS
SET CANONICAL_PLAYER_ID = CAFC_PLAYER_ID
WHERE CANONICAL_PLAYER_ID IS NULL AND CAFC_PLAYER_ID IS NOT NULL
  AND CAFC_PLAYER_ID IN (SELECT CAFC_PLAYER_ID FROM ${CORE}.PLAYERS);

UPDATE ${CORE}.PLAYER_LIST_ITEMS li
SET CANONICAL_PLAYER_ID = r.CAFC_PLAYER_ID
FROM ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
WHERE li.CANONICAL_PLAYER_ID IS NULL
  AND li.PLAYER_ID IS NOT NULL
  AND r.SOURCE_SYSTEM = 'IMPECT'
  AND r.SOURCE_PLAYER_ID = TO_VARCHAR(li.PLAYER_ID);

-- ---- PLAYER_INFORMATION (intel) --------------------------------------------------
-- PLAYER_ID is overloaded here. Verified against live data: DATA_SOURCE is 'external' for
-- almost every row and NULL for a few, and in both cases PLAYER_ID is an IMPECT id. Only
-- rows explicitly marked 'internal' carry a CAFC id.
ALTER TABLE ${CORE}.PLAYER_INFORMATION ADD COLUMN IF NOT EXISTS CANONICAL_PLAYER_ID NUMBER(38,0);

UPDATE ${CORE}.PLAYER_INFORMATION
SET CANONICAL_PLAYER_ID = PLAYER_ID
WHERE CANONICAL_PLAYER_ID IS NULL
  AND PLAYER_ID IS NOT NULL
  AND DATA_SOURCE = 'internal'
  AND PLAYER_ID IN (SELECT CAFC_PLAYER_ID FROM ${CORE}.PLAYERS);

UPDATE ${CORE}.PLAYER_INFORMATION pi
SET CANONICAL_PLAYER_ID = r.CAFC_PLAYER_ID
FROM ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
WHERE pi.CANONICAL_PLAYER_ID IS NULL
  AND pi.PLAYER_ID IS NOT NULL
  AND pi.DATA_SOURCE IS DISTINCT FROM 'internal'
  AND r.SOURCE_SYSTEM = 'IMPECT'
  AND r.SOURCE_PLAYER_ID = TO_VARCHAR(pi.PLAYER_ID);

-- ---- PLAYER_LIST_FLAGS: UNIVERSAL_ID 'internal_N' / 'external_N' -> number --------
ALTER TABLE ${CORE}.PLAYER_LIST_FLAGS ADD COLUMN IF NOT EXISTS CAFC_PLAYER_ID NUMBER(38,0);

UPDATE ${CORE}.PLAYER_LIST_FLAGS
SET CAFC_PLAYER_ID = TRY_TO_NUMBER(REGEXP_SUBSTR(UNIVERSAL_ID, '^internal_([0-9]+)$', 1, 1, 'e', 1))
WHERE CAFC_PLAYER_ID IS NULL AND REGEXP_LIKE(UNIVERSAL_ID, '^internal_[0-9]+$');

UPDATE ${CORE}.PLAYER_LIST_FLAGS fl
SET CAFC_PLAYER_ID = r.CAFC_PLAYER_ID
FROM ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
WHERE fl.CAFC_PLAYER_ID IS NULL
  AND REGEXP_LIKE(fl.UNIVERSAL_ID, '^external_[0-9]+$')
  AND r.SOURCE_SYSTEM = 'IMPECT'
  AND r.SOURCE_PLAYER_ID = REGEXP_SUBSTR(fl.UNIVERSAL_ID, '^external_([0-9]+)$', 1, 1, 'e', 1);

-- ---- PLAYER_RECOMMENDATIONS: LINKED_UNIVERSAL_ID -> LINKED_CANONICAL_PLAYER_ID ---------
ALTER TABLE ${CORE}.PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS LINKED_CANONICAL_PLAYER_ID NUMBER(38,0);

UPDATE ${CORE}.PLAYER_RECOMMENDATIONS
SET LINKED_CANONICAL_PLAYER_ID = TRY_TO_NUMBER(REGEXP_SUBSTR(LINKED_UNIVERSAL_ID, '^internal_([0-9]+)$', 1, 1, 'e', 1))
WHERE LINKED_CANONICAL_PLAYER_ID IS NULL AND REGEXP_LIKE(LINKED_UNIVERSAL_ID, '^internal_[0-9]+$');

UPDATE ${CORE}.PLAYER_RECOMMENDATIONS pr
SET LINKED_CANONICAL_PLAYER_ID = r.CAFC_PLAYER_ID
FROM ${CORE}.CORE_PLAYER_ID_RESOLUTIONS r
WHERE pr.LINKED_CANONICAL_PLAYER_ID IS NULL
  AND REGEXP_LIKE(pr.LINKED_UNIVERSAL_ID, '^external_[0-9]+$')
  AND r.SOURCE_SYSTEM = 'IMPECT'
  AND r.SOURCE_PLAYER_ID = REGEXP_SUBSTR(pr.LINKED_UNIVERSAL_ID, '^external_([0-9]+)$', 1, 1, 'e', 1);
