-- @sync-until-cutover: recommendations
-- 030_agents.sql
-- 3NF: agent facts (name/agency/email/phone) are copied onto every recommendation,
-- and agency facts depend on the agent, not the recommendation. They are NOT
-- derivable from SUBMITTED_BY_USER_ID because staff also enter recommendations on
-- an agent's behalf. Introduce AGENCIES <- AGENTS and point recommendations and
-- login profiles at AGENTS.
--
-- AGENTS/AGENCIES are identity tables (ids are referenced), so their backfill is
-- insert-only: existing ids are never rewritten or deleted by a re-run. The AGENT_ID links on
-- recommendations/profiles are a full recompute (agent details are edited in place through the
-- agent portal), so this whole file is sync-until-cutover for the recommendations domain.

-- Shared key functions: migration and (later) the app compute identical keys.
CREATE OR REPLACE FUNCTION ${CORE}.NORMALIZE_NAME_KEY(v VARCHAR)
RETURNS VARCHAR
AS $$ NULLIF(LOWER(REGEXP_REPLACE(TRIM(v), '\\s+', ' ')), '') $$;

-- Email wins; otherwise name+agency. NULL when there is nothing to identify by.
CREATE OR REPLACE FUNCTION ${CORE}.AGENT_KEY(agent_name VARCHAR, agency VARCHAR, email VARCHAR)
RETURNS VARCHAR
AS $$
    CASE
        WHEN NULLIF(LOWER(TRIM(email)), '') IS NOT NULL THEN 'e:' || LOWER(TRIM(email))
        WHEN ${CORE}.NORMALIZE_NAME_KEY(agent_name) IS NOT NULL
            THEN 'n:' || ${CORE}.NORMALIZE_NAME_KEY(agent_name) || '|' || COALESCE(${CORE}.NORMALIZE_NAME_KEY(agency), '')
    END
$$;

CREATE TABLE IF NOT EXISTS ${CORE}.AGENCIES (
    AGENCY_ID   NUMBER(38,0) NOT NULL AUTOINCREMENT,
    AGENCY_NAME VARCHAR(255) NOT NULL,
    AGENCY_KEY  VARCHAR(255) NOT NULL,
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_AGENCIES PRIMARY KEY (AGENCY_ID),
    CONSTRAINT UQ_AGENCIES_KEY UNIQUE (AGENCY_KEY)
);

CREATE TABLE IF NOT EXISTS ${CORE}.AGENTS (
    AGENT_ID     NUMBER(38,0) NOT NULL AUTOINCREMENT,
    AGENCY_ID    NUMBER(38,0),
    AGENT_NAME   VARCHAR(255),
    AGENT_EMAIL  VARCHAR(255),
    AGENT_NUMBER VARCHAR(100),
    AGENT_KEY    VARCHAR(600) NOT NULL,
    CREATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_AGENTS PRIMARY KEY (AGENT_ID),
    CONSTRAINT UQ_AGENTS_KEY UNIQUE (AGENT_KEY),
    CONSTRAINT FK_AGENTS_AGENCY FOREIGN KEY (AGENCY_ID) REFERENCES ${CORE}.AGENCIES (AGENCY_ID)
);

-- Candidate rows from both places agent facts live today.
CREATE OR REPLACE TEMPORARY TABLE ${CORE}.AGENT_SOURCE_ROWS AS
SELECT AGENT_NAME, AGENCY, AGENT_EMAIL, AGENT_NUMBER, TS, PRIORITY
FROM (
    SELECT AGENT_NAME, AGENCY, AGENT_EMAIL, AGENT_NUMBER,
           COALESCE(UPDATED_AT, CREATED_AT) AS TS, 1 AS PRIORITY
    FROM ${CORE}.PLAYER_RECOMMENDATIONS
    UNION ALL
    SELECT AGENT_NAME, AGENCY, AGENT_EMAIL, AGENT_NUMBER,
           COALESCE(UPDATED_AT, CREATED_AT) AS TS, 2 AS PRIORITY
    FROM ${CORE}.AGENT_PROFILES
)
WHERE ${CORE}.AGENT_KEY(AGENT_NAME, AGENCY, AGENT_EMAIL) IS NOT NULL;

-- Agencies (one per normalized name), latest spelling wins.
MERGE INTO ${CORE}.AGENCIES t
USING (
    SELECT ${CORE}.NORMALIZE_NAME_KEY(AGENCY) AS AGENCY_KEY, TRIM(AGENCY) AS AGENCY_NAME
    FROM ${CORE}.AGENT_SOURCE_ROWS
    WHERE ${CORE}.NORMALIZE_NAME_KEY(AGENCY) IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ${CORE}.NORMALIZE_NAME_KEY(AGENCY) ORDER BY TS DESC NULLS LAST) = 1
) s ON t.AGENCY_KEY = s.AGENCY_KEY
WHEN NOT MATCHED THEN INSERT (AGENCY_NAME, AGENCY_KEY) VALUES (s.AGENCY_NAME, s.AGENCY_KEY);

-- Agents (one per AGENT_KEY), latest contact details win.
MERGE INTO ${CORE}.AGENTS t
USING (
    SELECT src.AGENT_KEY, src.AGENT_NAME, src.AGENT_EMAIL, src.AGENT_NUMBER, ag.AGENCY_ID
    FROM (
        SELECT ${CORE}.AGENT_KEY(AGENT_NAME, AGENCY, AGENT_EMAIL) AS AGENT_KEY,
               TRIM(AGENT_NAME)   AS AGENT_NAME,
               TRIM(AGENT_EMAIL)  AS AGENT_EMAIL,
               TRIM(AGENT_NUMBER) AS AGENT_NUMBER,
               ${CORE}.NORMALIZE_NAME_KEY(AGENCY) AS AGENCY_KEY
        FROM ${CORE}.AGENT_SOURCE_ROWS
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY ${CORE}.AGENT_KEY(AGENT_NAME, AGENCY, AGENT_EMAIL)
            ORDER BY TS DESC NULLS LAST, PRIORITY
        ) = 1
    ) src
    LEFT JOIN ${CORE}.AGENCIES ag ON ag.AGENCY_KEY = src.AGENCY_KEY
) s ON t.AGENT_KEY = s.AGENT_KEY
WHEN NOT MATCHED THEN INSERT (AGENCY_ID, AGENT_NAME, AGENT_EMAIL, AGENT_NUMBER, AGENT_KEY)
VALUES (s.AGENCY_ID, s.AGENT_NAME, s.AGENT_EMAIL, s.AGENT_NUMBER, s.AGENT_KEY);

-- Point the existing tables at AGENTS (legacy columns stay until contract).
ALTER TABLE ${CORE}.PLAYER_RECOMMENDATIONS ADD COLUMN IF NOT EXISTS AGENT_ID NUMBER(38,0);
ALTER TABLE ${CORE}.AGENT_PROFILES         ADD COLUMN IF NOT EXISTS AGENT_ID NUMBER(38,0);

UPDATE ${CORE}.PLAYER_RECOMMENDATIONS pr
SET AGENT_ID = a.AGENT_ID
FROM ${CORE}.AGENTS a
WHERE a.AGENT_KEY = ${CORE}.AGENT_KEY(pr.AGENT_NAME, pr.AGENCY, pr.AGENT_EMAIL)
  AND pr.AGENT_ID IS DISTINCT FROM a.AGENT_ID;

UPDATE ${CORE}.AGENT_PROFILES ap
SET AGENT_ID = a.AGENT_ID
FROM ${CORE}.AGENTS a
WHERE a.AGENT_KEY = ${CORE}.AGENT_KEY(ap.AGENT_NAME, ap.AGENCY, ap.AGENT_EMAIL)
  AND ap.AGENT_ID IS DISTINCT FROM a.AGENT_ID;
