-- @sync-until-cutover: recommendations
-- 040_recommendation_terms.sql
-- 1NF: the TRANSFER_FEE_* / CURRENT_WAGES_* / EXPECTED_WAGES_* column triplets are a
-- repeating group, and POTENTIAL_DEAL_TYPE is a comma-joined list.
--
-- These tables are DERIVED COPIES until the recommendations domain cuts over, so
-- each run rebuilds them (DELETE + INSERT in one transaction). The runner refuses
-- to run a file carrying @sync-until-cutover once that domain is marked cut over,
-- because after cutover the app writes these tables directly and a rebuild would
-- destroy data.

CREATE TABLE IF NOT EXISTS ${CORE}.RECOMMENDATION_TERMS (
    RECOMMENDATION_ID NUMBER(38,0) NOT NULL,
    TERM_TYPE         VARCHAR(20)  NOT NULL,   -- TRANSFER_FEE | CURRENT_WAGES | EXPECTED_WAGES
    AMOUNT            NUMBER(18,0),
    AMOUNT_MIN        NUMBER(18,0),
    AMOUNT_MAX        NUMBER(18,0),
    CURRENCY          VARCHAR(3),
    WAGE_BASIS        VARCHAR(20),             -- Gross | Net; NULL for TRANSFER_FEE
    RAW_TEXT          VARCHAR(1000),           -- legacy free text, kept only when no number was captured
    CONSTRAINT PK_RECOMMENDATION_TERMS PRIMARY KEY (RECOMMENDATION_ID, TERM_TYPE)
);

CREATE TABLE IF NOT EXISTS ${CORE}.RECOMMENDATION_DEAL_TYPES (
    RECOMMENDATION_ID NUMBER(38,0) NOT NULL,
    DEAL_TYPE_CODE    VARCHAR(100) NOT NULL,
    CONSTRAINT PK_RECOMMENDATION_DEAL_TYPES PRIMARY KEY (RECOMMENDATION_ID, DEAL_TYPE_CODE),
    CONSTRAINT FK_REC_DEAL_TYPES_TYPE FOREIGN KEY (DEAL_TYPE_CODE)    REFERENCES ${CORE}.DEAL_TYPES (CODE)
);

BEGIN;

DELETE FROM ${CORE}.RECOMMENDATION_TERMS;

INSERT INTO ${CORE}.RECOMMENDATION_TERMS
    (RECOMMENDATION_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, CURRENCY, WAGE_BASIS, RAW_TEXT)
SELECT ID, 'TRANSFER_FEE', TRANSFER_FEE_AMOUNT, TRANSFER_FEE_MIN, TRANSFER_FEE_MAX,
       NULLIF(TRIM(TRANSFER_FEE_CURRENCY), ''), NULL,
       CASE WHEN COALESCE(TRANSFER_FEE_AMOUNT, TRANSFER_FEE_MIN, TRANSFER_FEE_MAX) IS NULL
            THEN NULLIF(TRIM(TO_VARCHAR(TRANSFER_FEE)), '') END
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE COALESCE(TRANSFER_FEE_AMOUNT, TRANSFER_FEE_MIN, TRANSFER_FEE_MAX) IS NOT NULL
   OR NULLIF(TRIM(TO_VARCHAR(TRANSFER_FEE)), '') IS NOT NULL;

INSERT INTO ${CORE}.RECOMMENDATION_TERMS
    (RECOMMENDATION_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, CURRENCY, WAGE_BASIS, RAW_TEXT)
SELECT ID, 'CURRENT_WAGES', CURRENT_WAGES_AMOUNT, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX,
       NULLIF(TRIM(CURRENT_WAGES_CURRENCY), ''), NULLIF(TRIM(WAGE_BASIS), ''),
       CASE WHEN COALESCE(CURRENT_WAGES_AMOUNT, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX) IS NULL
            THEN NULLIF(TRIM(TO_VARCHAR(CURRENT_WAGES)), '') END
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE COALESCE(CURRENT_WAGES_AMOUNT, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX) IS NOT NULL
   OR NULLIF(TRIM(TO_VARCHAR(CURRENT_WAGES)), '') IS NOT NULL;

INSERT INTO ${CORE}.RECOMMENDATION_TERMS
    (RECOMMENDATION_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, CURRENCY, WAGE_BASIS, RAW_TEXT)
SELECT ID, 'EXPECTED_WAGES', EXPECTED_WAGES_AMOUNT, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX,
       NULLIF(TRIM(EXPECTED_WAGES_CURRENCY), ''), NULLIF(TRIM(WAGE_BASIS), ''),
       CASE WHEN COALESCE(EXPECTED_WAGES_AMOUNT, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX) IS NULL
            THEN NULLIF(TRIM(TO_VARCHAR(EXPECTED_WAGES)), '') END
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE COALESCE(EXPECTED_WAGES_AMOUNT, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX) IS NOT NULL
   OR NULLIF(TRIM(TO_VARCHAR(EXPECTED_WAGES)), '') IS NOT NULL;

DELETE FROM ${CORE}.RECOMMENDATION_DEAL_TYPES;

INSERT INTO ${CORE}.RECOMMENDATION_DEAL_TYPES (RECOMMENDATION_ID, DEAL_TYPE_CODE)
SELECT DISTINCT r.ID, TRIM(s.VALUE)
FROM ${CORE}.PLAYER_RECOMMENDATIONS r, LATERAL SPLIT_TO_TABLE(r.POTENTIAL_DEAL_TYPE, ',') s
WHERE TRIM(s.VALUE) <> '';

COMMIT;
