-- @sync-until-cutover: intel
-- 050_intel.sql
-- PLAYER_INFORMATION (intel) is one wide table for three report subtypes.
--   3NF  : CONTACT_ORGANISATION depends on the contact  -> CONTACTS
--   3NF  : reference-form columns only apply to INTEL_TYPE='reference_form'
--          -> 1:1 subtype table INTEL_REFERENCE_DETAILS
--   1NF  : POTENTIAL_DEAL_TYPE / RELATIONSHIP_TO_PLAYER are comma-joined lists
--          -> junction tables; wage/fee column groups -> INTEL_TERMS
-- CONTACTS is an identity table (insert-only). The other new tables are derived
-- copies, rebuilt on each run until intel cuts over (see 040 header).

CREATE TABLE IF NOT EXISTS ${CORE}.CONTACTS (
    CONTACT_ID           NUMBER(38,0) NOT NULL AUTOINCREMENT,
    CONTACT_NAME         VARCHAR(255) NOT NULL,
    CONTACT_ORGANISATION VARCHAR(255),
    CONTACT_KEY          VARCHAR(600) NOT NULL,
    CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTACTS PRIMARY KEY (CONTACT_ID),
    CONSTRAINT UQ_CONTACTS_KEY UNIQUE (CONTACT_KEY)
);

MERGE INTO ${CORE}.CONTACTS t
USING (
    SELECT ${CORE}.NORMALIZE_NAME_KEY(CONTACT_NAME) || '|' || COALESCE(${CORE}.NORMALIZE_NAME_KEY(CONTACT_ORGANISATION), '') AS CONTACT_KEY,
           TRIM(CONTACT_NAME) AS CONTACT_NAME,
           NULLIF(TRIM(CONTACT_ORGANISATION), '') AS CONTACT_ORGANISATION
    FROM ${CORE}.PLAYER_INFORMATION
    WHERE ${CORE}.NORMALIZE_NAME_KEY(CONTACT_NAME) IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ${CORE}.NORMALIZE_NAME_KEY(CONTACT_NAME) || '|' || COALESCE(${CORE}.NORMALIZE_NAME_KEY(CONTACT_ORGANISATION), '')
        ORDER BY CREATED_AT DESC NULLS LAST
    ) = 1
) s ON t.CONTACT_KEY = s.CONTACT_KEY
WHEN NOT MATCHED THEN INSERT (CONTACT_NAME, CONTACT_ORGANISATION, CONTACT_KEY)
    VALUES (s.CONTACT_NAME, s.CONTACT_ORGANISATION, s.CONTACT_KEY);

ALTER TABLE ${CORE}.PLAYER_INFORMATION ADD COLUMN IF NOT EXISTS CONTACT_ID NUMBER(38,0);

UPDATE ${CORE}.PLAYER_INFORMATION pi
SET CONTACT_ID = c.CONTACT_ID
FROM ${CORE}.CONTACTS c
WHERE pi.CONTACT_ID IS NULL
  AND ${CORE}.NORMALIZE_NAME_KEY(pi.CONTACT_NAME) IS NOT NULL
  AND c.CONTACT_KEY = ${CORE}.NORMALIZE_NAME_KEY(pi.CONTACT_NAME) || '|' || COALESCE(${CORE}.NORMALIZE_NAME_KEY(pi.CONTACT_ORGANISATION), '');

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_TERMS (
    INTEL_REPORT_ID NUMBER(38,0) NOT NULL,
    TERM_TYPE       VARCHAR(20)  NOT NULL,   -- TRANSFER_FEE | CURRENT_WAGES | EXPECTED_WAGES
    AMOUNT          NUMBER(18,0),
    AMOUNT_MIN      NUMBER(18,0),
    AMOUNT_MAX      NUMBER(18,0),
    RAW_TEXT        VARCHAR(1000),
    CONSTRAINT PK_INTEL_TERMS PRIMARY KEY (INTEL_REPORT_ID, TERM_TYPE)
);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_DEAL_TYPES (
    INTEL_REPORT_ID NUMBER(38,0) NOT NULL,
    DEAL_TYPE_CODE  VARCHAR(100) NOT NULL,
    CONSTRAINT PK_INTEL_DEAL_TYPES PRIMARY KEY (INTEL_REPORT_ID, DEAL_TYPE_CODE),
    CONSTRAINT FK_INTEL_DEAL_TYPES_TYPE   FOREIGN KEY (DEAL_TYPE_CODE)  REFERENCES ${CORE}.DEAL_TYPES (CODE)
);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_RELATIONSHIPS (
    INTEL_REPORT_ID   NUMBER(38,0) NOT NULL,
    RELATIONSHIP_CODE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_INTEL_RELATIONSHIPS PRIMARY KEY (INTEL_REPORT_ID, RELATIONSHIP_CODE),
    CONSTRAINT FK_INTEL_REL_TYPE   FOREIGN KEY (RELATIONSHIP_CODE) REFERENCES ${CORE}.RELATIONSHIP_TYPES (CODE)
);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_REFERENCE_DETAILS (
    INTEL_REPORT_ID           NUMBER(38,0) NOT NULL,
    LENGTH_OF_RELATIONSHIP    VARCHAR(100),
    RELEVANCE_OF_RELATIONSHIP VARCHAR(100),
    REFERENCE_RATING          VARCHAR(100),
    CONSTRAINT PK_INTEL_REFERENCE_DETAILS PRIMARY KEY (INTEL_REPORT_ID)
);

BEGIN;

DELETE FROM ${CORE}.INTEL_TERMS;

INSERT INTO ${CORE}.INTEL_TERMS (INTEL_REPORT_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, RAW_TEXT)
SELECT ID, 'TRANSFER_FEE', NULL, NULL, NULL, NULLIF(TRIM(TO_VARCHAR(TRANSFER_FEE)), '')
FROM ${CORE}.PLAYER_INFORMATION
WHERE NULLIF(TRIM(TO_VARCHAR(TRANSFER_FEE)), '') IS NOT NULL;

INSERT INTO ${CORE}.INTEL_TERMS (INTEL_REPORT_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, RAW_TEXT)
SELECT ID, 'CURRENT_WAGES', CURRENT_WAGES, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX, NULL
FROM ${CORE}.PLAYER_INFORMATION
WHERE COALESCE(CURRENT_WAGES, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX) IS NOT NULL;

INSERT INTO ${CORE}.INTEL_TERMS (INTEL_REPORT_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, RAW_TEXT)
SELECT ID, 'EXPECTED_WAGES', EXPECTED_WAGES, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX, NULL
FROM ${CORE}.PLAYER_INFORMATION
WHERE COALESCE(EXPECTED_WAGES, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX) IS NOT NULL;

DELETE FROM ${CORE}.INTEL_DEAL_TYPES;

INSERT INTO ${CORE}.INTEL_DEAL_TYPES (INTEL_REPORT_ID, DEAL_TYPE_CODE)
SELECT DISTINCT i.ID, ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE)
FROM ${CORE}.PLAYER_INFORMATION i, LATERAL SPLIT_TO_TABLE(i.POTENTIAL_DEAL_TYPE, ',') s
WHERE ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE) IS NOT NULL;

DELETE FROM ${CORE}.INTEL_RELATIONSHIPS;

INSERT INTO ${CORE}.INTEL_RELATIONSHIPS (INTEL_REPORT_ID, RELATIONSHIP_CODE)
SELECT DISTINCT i.ID, TRIM(s.VALUE)
FROM ${CORE}.PLAYER_INFORMATION i, LATERAL SPLIT_TO_TABLE(i.RELATIONSHIP_TO_PLAYER, ',') s
WHERE TRIM(s.VALUE) <> '';

DELETE FROM ${CORE}.INTEL_REFERENCE_DETAILS;

INSERT INTO ${CORE}.INTEL_REFERENCE_DETAILS
    (INTEL_REPORT_ID, LENGTH_OF_RELATIONSHIP, RELEVANCE_OF_RELATIONSHIP, REFERENCE_RATING)
SELECT ID, LENGTH_OF_RELATIONSHIP, RELEVANCE_OF_RELATIONSHIP, REFERENCE_RATING
FROM ${CORE}.PLAYER_INFORMATION
WHERE INTEL_TYPE = 'reference_form';

COMMIT;
