-- @sync-until-cutover: intel
-- 050_intel.sql
-- The NORMALIZED tables for intel reports (legacy PLAYER_INFORMATION, one wide table for three report subtypes):
--   INTEL_REPORTS            the report's own facts
--   CONTACTS                 who gave the information (3NF: the organisation depends on the contact, not on the report)
--   INTEL_TERMS              transfer fee text / current wages / expected wages (amount, min, max)
--   INTEL_DEAL_TYPES         potential deal types, one row per item with SEQ (1NF: was a comma list)
--   INTEL_RELATIONSHIPS      relationship to player, one row per item with SEQ (1NF: was a comma list)
--   INTEL_REFERENCE_DETAILS  1:1 subtype table, only for INTEL_TYPE = 'reference_form' (3NF)
--
-- CONTACTS is keyed on the EXACT name and organisation strings the reports carry, so the compat view hands the app
-- the same text it saved. Contacts are an identity table: insert-only, never rebuilt.
-- INTEL_TERMS.AMOUNT holds the legacy single-number wage verbatim (it equals MIN = MAX on all but one row, and that
-- row is kept as it is). Transfer fee has no amount in intel, only the typed text, in RAW_TEXT.
-- INTEL_DEAL_TYPES stores the canonical label ('Permanent Transfer'), the compat view maps it back to the legacy code.
--
-- Derived copy of PLAYER_INFORMATION until intel cuts over; the rebuild runs in one transaction and the runner
-- refuses to re-run it after `--mark-cutover intel`.

CREATE TABLE IF NOT EXISTS ${CORE}.CONTACTS (
    CONTACT_ID           NUMBER(38,0) NOT NULL AUTOINCREMENT,
    CONTACT_NAME         VARCHAR      NOT NULL,
    CONTACT_ORGANISATION VARCHAR,
    CONTACT_KEY          VARCHAR      NOT NULL,   -- CONTACT_NAME || CHR(31) || COALESCE(CONTACT_ORGANISATION, '')
    CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTACTS PRIMARY KEY (CONTACT_ID),
    CONSTRAINT UQ_CONTACTS_KEY UNIQUE (CONTACT_KEY)
);

MERGE INTO ${CORE}.CONTACTS t
USING (
    SELECT CONTACT_NAME || CHR(31) || COALESCE(CONTACT_ORGANISATION, '') AS CONTACT_KEY,
           CONTACT_NAME, CONTACT_ORGANISATION
    FROM ${CORE}.PLAYER_INFORMATION
    WHERE CONTACT_NAME IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CONTACT_NAME || CHR(31) || COALESCE(CONTACT_ORGANISATION, '')
        ORDER BY ID
    ) = 1
) s ON t.CONTACT_KEY = s.CONTACT_KEY
WHEN NOT MATCHED THEN INSERT (CONTACT_NAME, CONTACT_ORGANISATION, CONTACT_KEY)
    VALUES (s.CONTACT_NAME, s.CONTACT_ORGANISATION, s.CONTACT_KEY);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_REPORTS (
    ID                  NUMBER(38,0) NOT NULL,
    USER_ID             NUMBER(38,0),
    PLAYER_ID           NUMBER(38,0),            -- as the legacy table: an IMPECT id or a CAFC id, see DATA_SOURCE
    DATA_SOURCE         VARCHAR(10),
    CANONICAL_PLAYER_ID NUMBER(38,0),            -- the resolved CAFC player id (kept current by the write path)
    CONTACT_ID          NUMBER(38,0),
    INTEL_TYPE          VARCHAR      NOT NULL,
    DATE_OF_INFORMATION DATE,
    CONTRACT_EXPIRY     DATE,
    CONTRACT_OPTIONS    VARCHAR,
    CONVERSATION_NOTES  VARCHAR,
    ACTION_REQUIRED     VARCHAR,                 -- the 'recommendation' the scout types; the legacy column name is kept
    CREATED_AT          TIMESTAMP_NTZ,
    CONSTRAINT PK_INTEL_REPORTS PRIMARY KEY (ID),
    CONSTRAINT FK_INTEL_REPORTS_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES ${CORE}.CONTACTS (CONTACT_ID)
);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_TERMS (
    INTEL_REPORT_ID NUMBER(38,0) NOT NULL,
    TERM_TYPE       VARCHAR(20)  NOT NULL,       -- TRANSFER_FEE | CURRENT_WAGES | EXPECTED_WAGES
    AMOUNT          NUMBER(38,0),
    AMOUNT_MIN      NUMBER(38,0),
    AMOUNT_MAX      NUMBER(38,0),
    RAW_TEXT        VARCHAR,
    CONSTRAINT PK_INTEL_TERMS PRIMARY KEY (INTEL_REPORT_ID, TERM_TYPE)
);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_DEAL_TYPES (
    INTEL_REPORT_ID NUMBER(38,0) NOT NULL,
    DEAL_TYPE_CODE  VARCHAR(100) NOT NULL,
    SEQ             NUMBER(5,0)  NOT NULL,
    CONSTRAINT PK_INTEL_DEAL_TYPES PRIMARY KEY (INTEL_REPORT_ID, DEAL_TYPE_CODE),
    CONSTRAINT FK_INTEL_DEAL_TYPES_TYPE FOREIGN KEY (DEAL_TYPE_CODE) REFERENCES ${CORE}.DEAL_TYPES (CODE)
);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_RELATIONSHIPS (
    INTEL_REPORT_ID   NUMBER(38,0) NOT NULL,
    RELATIONSHIP_CODE VARCHAR(100) NOT NULL,
    SEQ               NUMBER(5,0)  NOT NULL,
    CONSTRAINT PK_INTEL_RELATIONSHIPS PRIMARY KEY (INTEL_REPORT_ID, RELATIONSHIP_CODE),
    CONSTRAINT FK_INTEL_REL_TYPE FOREIGN KEY (RELATIONSHIP_CODE) REFERENCES ${CORE}.RELATIONSHIP_TYPES (CODE)
);

CREATE TABLE IF NOT EXISTS ${CORE}.INTEL_REFERENCE_DETAILS (
    INTEL_REPORT_ID           NUMBER(38,0) NOT NULL,
    LENGTH_OF_RELATIONSHIP    VARCHAR,
    RELEVANCE_OF_RELATIONSHIP VARCHAR,
    REFERENCE_RATING          VARCHAR,
    CONSTRAINT PK_INTEL_REFERENCE_DETAILS PRIMARY KEY (INTEL_REPORT_ID)
);

BEGIN;

DELETE FROM ${CORE}.INTEL_REPORTS;

INSERT INTO ${CORE}.INTEL_REPORTS
    (ID, USER_ID, PLAYER_ID, DATA_SOURCE, CANONICAL_PLAYER_ID, CONTACT_ID, INTEL_TYPE, DATE_OF_INFORMATION,
     CONTRACT_EXPIRY, CONTRACT_OPTIONS, CONVERSATION_NOTES, ACTION_REQUIRED, CREATED_AT)
SELECT i.ID, i.USER_ID, i.PLAYER_ID, i.DATA_SOURCE, i.CANONICAL_PLAYER_ID, c.CONTACT_ID, i.INTEL_TYPE,
       i.DATE_OF_INFORMATION, i.CONTRACT_EXPIRY, i.CONTRACT_OPTIONS, i.CONVERSATION_NOTES, i.ACTION_REQUIRED, i.CREATED_AT
FROM ${CORE}.PLAYER_INFORMATION i
LEFT JOIN ${CORE}.CONTACTS c
       ON c.CONTACT_KEY = i.CONTACT_NAME || CHR(31) || COALESCE(i.CONTACT_ORGANISATION, '')
      AND i.CONTACT_NAME IS NOT NULL;

DELETE FROM ${CORE}.INTEL_TERMS;

INSERT INTO ${CORE}.INTEL_TERMS (INTEL_REPORT_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, RAW_TEXT)
SELECT ID, 'TRANSFER_FEE', NULL, NULL, NULL, TRANSFER_FEE
FROM ${CORE}.PLAYER_INFORMATION
WHERE TRANSFER_FEE IS NOT NULL;

INSERT INTO ${CORE}.INTEL_TERMS (INTEL_REPORT_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, RAW_TEXT)
SELECT ID, 'CURRENT_WAGES', CURRENT_WAGES, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX, NULL
FROM ${CORE}.PLAYER_INFORMATION
WHERE COALESCE(CURRENT_WAGES, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX) IS NOT NULL;

INSERT INTO ${CORE}.INTEL_TERMS (INTEL_REPORT_ID, TERM_TYPE, AMOUNT, AMOUNT_MIN, AMOUNT_MAX, RAW_TEXT)
SELECT ID, 'EXPECTED_WAGES', EXPECTED_WAGES, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX, NULL
FROM ${CORE}.PLAYER_INFORMATION
WHERE COALESCE(EXPECTED_WAGES, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX) IS NOT NULL;

DELETE FROM ${CORE}.INTEL_DEAL_TYPES;

INSERT INTO ${CORE}.INTEL_DEAL_TYPES (INTEL_REPORT_ID, DEAL_TYPE_CODE, SEQ)
SELECT i.ID, ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE), MIN(s.INDEX)
FROM ${CORE}.PLAYER_INFORMATION i, LATERAL SPLIT_TO_TABLE(i.POTENTIAL_DEAL_TYPE, ',') s
WHERE ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE) IS NOT NULL
GROUP BY i.ID, ${CORE}.CANONICAL_DEAL_TYPE(s.VALUE);

DELETE FROM ${CORE}.INTEL_RELATIONSHIPS;

INSERT INTO ${CORE}.INTEL_RELATIONSHIPS (INTEL_REPORT_ID, RELATIONSHIP_CODE, SEQ)
SELECT i.ID, TRIM(s.VALUE), MIN(s.INDEX)
FROM ${CORE}.PLAYER_INFORMATION i, LATERAL SPLIT_TO_TABLE(i.RELATIONSHIP_TO_PLAYER, ',') s
WHERE TRIM(s.VALUE) <> ''
GROUP BY i.ID, TRIM(s.VALUE);

DELETE FROM ${CORE}.INTEL_REFERENCE_DETAILS;

INSERT INTO ${CORE}.INTEL_REFERENCE_DETAILS
    (INTEL_REPORT_ID, LENGTH_OF_RELATIONSHIP, RELEVANCE_OF_RELATIONSHIP, REFERENCE_RATING)
SELECT ID, LENGTH_OF_RELATIONSHIP, RELEVANCE_OF_RELATIONSHIP, REFERENCE_RATING
FROM ${CORE}.PLAYER_INFORMATION
WHERE INTEL_TYPE = 'reference_form';

COMMIT;
