-- 061_compat_recommendations.sql
-- The LEGACY-SHAPED compatibility view over the normalized tables: same 41 columns, same order, same values
-- as the legacy PLAYER_RECOMMENDATIONS table, but assembled from RECOMMENDATIONS + AGENT_PROFILES +
-- RECOMMENDATION_TERMS + the four junction tables. This is what lets the app keep its 251 read call sites
-- unchanged: at the swap the legacy table is renamed *_LEGACY and a view with the legacy NAME selects from this.
--
-- It is a pure view (no data), so re-creating it is safe at any time. It is checked against the real legacy
-- table by parity/recommendations.sql before any swap.
--
-- Column order AND column TYPES are part of the contract. Order: the app reads some rows by position. Types: the
-- app applies TRY_CAST to some columns, and Snowflake rejects TRY_CAST(NUMBER(18,0) AS NUMBER(38,0)); found by running
-- the real endpoints against a swapped schema. Every column is therefore CAST to the type the LIVE legacy table has
-- (generated from INFORMATION_SCHEMA.COLUMNS of CAFC_DB.CORE.PLAYER_RECOMMENDATIONS, 2026-09-30).

CREATE OR REPLACE VIEW ${CORE}.V_COMPAT_PLAYER_RECOMMENDATIONS AS
WITH agreement AS (
    SELECT RECOMMENDATION_ID, LISTAGG(AGREEMENT_TYPE_CODE, ',') WITHIN GROUP (ORDER BY SEQ) AS V
    FROM ${CORE}.RECOMMENDATION_AGREEMENT_TYPES GROUP BY RECOMMENDATION_ID
), options AS (
    SELECT RECOMMENDATION_ID, LISTAGG(CONTRACT_OPTION_CODE, ',') WITHIN GROUP (ORDER BY SEQ) AS V
    FROM ${CORE}.RECOMMENDATION_CONTRACT_OPTIONS GROUP BY RECOMMENDATION_ID
), deals AS (
    SELECT RECOMMENDATION_ID, LISTAGG(DEAL_TYPE_CODE, ',') WITHIN GROUP (ORDER BY SEQ) AS V
    FROM ${CORE}.RECOMMENDATION_DEAL_TYPES GROUP BY RECOMMENDATION_ID
), positions AS (
    SELECT RECOMMENDATION_ID, LISTAGG(POSITION_CODE, ',') WITHIN GROUP (ORDER BY SEQ) AS V
    FROM ${CORE}.RECOMMENDATION_POSITIONS GROUP BY RECOMMENDATION_ID
), fee AS (
    SELECT * FROM ${CORE}.RECOMMENDATION_TERMS WHERE TERM_TYPE = 'TRANSFER_FEE'
), cur AS (
    SELECT * FROM ${CORE}.RECOMMENDATION_TERMS WHERE TERM_TYPE = 'CURRENT_WAGES'
), exp AS (
    SELECT * FROM ${CORE}.RECOMMENDATION_TERMS WHERE TERM_TYPE = 'EXPECTED_WAGES'
)
SELECT
    CAST(r.ID AS NUMBER(38,0)) AS ID,
    CAST(ap.AGENT_NAME AS VARCHAR) AS AGENT_NAME,
    CAST(ap.AGENCY AS VARCHAR) AS AGENCY,
    CAST(ap.AGENT_EMAIL AS VARCHAR) AS AGENT_EMAIL,
    CAST(ap.AGENT_NUMBER AS VARCHAR) AS AGENT_NUMBER,
    CAST(r.DATE AS DATE) AS DATE,
    CAST(r.TRANSFERMARKT_LINK AS VARCHAR) AS TRANSFERMARKT_LINK,
    CAST(agreement.V AS VARCHAR) AS AGREEMENT_TYPE,
    CAST(r.CONTRACT_EXPIRY AS DATE) AS CONTRACT_EXPIRY,
    CAST(options.V AS VARCHAR) AS CONTRACT_OPTIONS,
    CAST(deals.V AS VARCHAR) AS POTENTIAL_DEAL_TYPE,
    CAST(r.TRANSFER_FEE_TEXT AS VARCHAR) AS TRANSFER_FEE,
    CAST(r.CURRENT_WAGES_LEGACY AS NUMBER(38,0)) AS CURRENT_WAGES,
    CAST(r.EXPECTED_WAGES_LEGACY AS NUMBER(38,0)) AS EXPECTED_WAGES,
    CAST(r.ADDITIONAL_INFO AS VARCHAR) AS ADDITIONAL_INFO,
    CAST(r.PLAYER_NAME AS VARCHAR(255)) AS PLAYER_NAME,
    CAST(r.SUBMITTED_BY_USER_ID AS NUMBER(38,0)) AS SUBMITTED_BY_USER_ID,
    CAST(r.STATUS AS VARCHAR(100)) AS STATUS,
    CAST(r.STATUS_UPDATED_AT AS TIMESTAMP_NTZ) AS STATUS_UPDATED_AT,
    CAST(r.STATUS_UPDATED_BY AS NUMBER(38,0)) AS STATUS_UPDATED_BY,
    CAST(r.INTERNAL_NOTES AS VARCHAR(5000)) AS INTERNAL_NOTES,
    CAST(r.UPDATED_AT AS TIMESTAMP_NTZ) AS UPDATED_AT,
    CAST(r.CREATED_AT AS TIMESTAMP_NTZ) AS CREATED_AT,
    CAST(exp.CURRENCY AS VARCHAR(3)) AS EXPECTED_WAGES_CURRENCY,
    CAST(exp.AMOUNT AS NUMBER(18,0)) AS EXPECTED_WAGES_AMOUNT,
    CAST(cur.CURRENCY AS VARCHAR(3)) AS CURRENT_WAGES_CURRENCY,
    CAST(cur.AMOUNT AS NUMBER(18,0)) AS CURRENT_WAGES_AMOUNT,
    CAST(fee.CURRENCY AS VARCHAR(3)) AS TRANSFER_FEE_CURRENCY,
    CAST(fee.AMOUNT AS NUMBER(18,0)) AS TRANSFER_FEE_AMOUNT,
    CAST(positions.V AS VARCHAR(255)) AS RECOMMENDED_POSITION,
    CAST(r.PLAYER_DATE_OF_BIRTH AS DATE) AS PLAYER_DATE_OF_BIRTH,
    CAST(r.AGENT_STATUS AS VARCHAR(100)) AS AGENT_STATUS,
    CAST(r.AGENT_STATUS_UPDATED_AT AS TIMESTAMP_NTZ) AS AGENT_STATUS_UPDATED_AT,
    CAST(exp.AMOUNT_MAX AS NUMBER(38,0)) AS EXPECTED_WAGES_MAX,
    CAST(exp.AMOUNT_MIN AS NUMBER(38,0)) AS EXPECTED_WAGES_MIN,
    CAST(cur.AMOUNT_MAX AS NUMBER(38,0)) AS CURRENT_WAGES_MAX,
    CAST(cur.AMOUNT_MIN AS NUMBER(38,0)) AS CURRENT_WAGES_MIN,
    CAST(r.WAGE_BASIS AS VARCHAR(10)) AS WAGE_BASIS,
    CAST(fee.AMOUNT_MAX AS NUMBER(38,0)) AS TRANSFER_FEE_MAX,
    CAST(fee.AMOUNT_MIN AS NUMBER(38,0)) AS TRANSFER_FEE_MIN,
    CAST(r.LINKED_UNIVERSAL_ID AS VARCHAR) AS LINKED_UNIVERSAL_ID
FROM ${CORE}.RECOMMENDATIONS r
LEFT JOIN ${CORE}.AGENT_PROFILES ap ON ap.USER_ID = r.SUBMITTED_BY_USER_ID
LEFT JOIN agreement ON agreement.RECOMMENDATION_ID = r.ID
LEFT JOIN options   ON options.RECOMMENDATION_ID   = r.ID
LEFT JOIN deals     ON deals.RECOMMENDATION_ID     = r.ID
LEFT JOIN positions ON positions.RECOMMENDATION_ID = r.ID
LEFT JOIN fee ON fee.RECOMMENDATION_ID = r.ID
LEFT JOIN cur ON cur.RECOMMENDATION_ID = r.ID
LEFT JOIN exp ON exp.RECOMMENDATION_ID = r.ID;
