-- 090_grants.sql
-- New tables do not inherit grants. App role: DML on tables the app will write,
-- read-only on lookups. Analyst/pipeline role: read-only everywhere.

GRANT SELECT ON ${CORE}.ROLES                   TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.REPORT_TYPES            TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.REPORT_PURPOSES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.SCOUTING_TYPES          TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.FLAG_CATEGORIES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.CLIP_CATEGORIES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.LIST_CATEGORIES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.LIST_STAGES             TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_STATUSES TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.INTEL_TYPES             TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.DEAL_TYPES              TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RELATIONSHIP_TYPES      TO ROLE APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.AGENCIES                TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.CONTACTS                TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATION_TERMS      TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATION_DEAL_TYPES TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_TERMS             TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_DEAL_TYPES        TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_RELATIONSHIPS     TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_REFERENCE_DETAILS TO ROLE APP_ROLE;

GRANT USAGE ON FUNCTION ${CORE}.NORMALIZE_NAME_KEY(VARCHAR)                   TO ROLE APP_ROLE;
GRANT USAGE ON FUNCTION ${CORE}.CANONICAL_DEAL_TYPE(VARCHAR)                  TO ROLE APP_ROLE;

GRANT SELECT ON ${CORE}.ROLES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.REPORT_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.REPORT_PURPOSES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.SCOUTING_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.FLAG_CATEGORIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.CLIP_CATEGORIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.LIST_CATEGORIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.LIST_STAGES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_STATUSES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.DEAL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RELATIONSHIP_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.AGENCIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.CONTACTS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_TERMS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_DEAL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_TERMS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_DEAL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_RELATIONSHIPS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_REFERENCE_DETAILS TO ROLE DEV_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_SCOUT_REPORT_KEYS TO ROLE DEV_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_PLAYER_LIST_ITEM_KEYS TO ROLE DEV_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_PLAYER_LIST_FLAG_KEYS TO ROLE DEV_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_RECOMMENDATION_KEYS TO ROLE DEV_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_INTEL_KEYS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.AGREEMENT_TYPES TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.AGREEMENT_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.CONTRACT_OPTIONS TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.CONTRACT_OPTIONS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDED_POSITIONS TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDED_POSITIONS TO ROLE DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATION_AGREEMENT_TYPES TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_AGREEMENT_TYPES TO ROLE DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATION_CONTRACT_OPTIONS TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_CONTRACT_OPTIONS TO ROLE DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATION_POSITIONS TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_POSITIONS TO ROLE DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATIONS TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATIONS TO ROLE DEV_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_COMPAT_PLAYER_RECOMMENDATIONS TO ROLE APP_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_COMPAT_PLAYER_RECOMMENDATIONS TO ROLE DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_REPORTS TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.INTEL_REPORTS TO ROLE DEV_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_COMPAT_PLAYER_INFORMATION TO ROLE APP_ROLE;
GRANT SELECT ON VIEW ${CORE}.V_COMPAT_PLAYER_INFORMATION TO ROLE DEV_ROLE;
GRANT USAGE ON FUNCTION ${CORE}.INTEL_DEAL_TYPE_CODE(VARCHAR) TO ROLE APP_ROLE;
