-- 090_grants.sql
-- New tables do not inherit grants. App role: DML on tables the app will write,
-- read-only on lookups. Analyst/pipeline role: read-only everywhere.

GRANT SELECT ON ${CORE}.ROLES                   TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.REPORT_TYPES            TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.REPORT_PURPOSES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.SCOUTING_TYPES          TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.FLAG_CATEGORIES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.CLIP_CATEGORIES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.LIST_CATEGORIES         TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.LIST_STAGES             TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_STATUSES TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.INTEL_TYPES             TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.DEAL_TYPES              TO ROLE APP_ROLE;
GRANT SELECT ON ${CORE}.RELATIONSHIP_TYPES      TO ROLE APP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.AGENCIES                TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.AGENTS                  TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.CONTACTS                TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATION_TERMS      TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.RECOMMENDATION_DEAL_TYPES TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_TERMS             TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_DEAL_TYPES        TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_RELATIONSHIPS     TO ROLE APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${CORE}.INTEL_REFERENCE_DETAILS TO ROLE APP_ROLE;

GRANT USAGE ON FUNCTION ${CORE}.NORMALIZE_NAME_KEY(VARCHAR)                   TO ROLE APP_ROLE;
GRANT USAGE ON FUNCTION ${CORE}.AGENT_KEY(VARCHAR, VARCHAR, VARCHAR)          TO ROLE APP_ROLE;

GRANT SELECT ON ${CORE}.ROLES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.REPORT_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.REPORT_PURPOSES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.SCOUTING_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.FLAG_CATEGORIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.CLIP_CATEGORIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.LIST_CATEGORIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.LIST_STAGES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_STATUSES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.DEAL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RELATIONSHIP_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.AGENCIES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.AGENTS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.CONTACTS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_TERMS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.RECOMMENDATION_DEAL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_TERMS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_DEAL_TYPES TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_RELATIONSHIPS TO ROLE DEV_ROLE;
GRANT SELECT ON ${CORE}.INTEL_REFERENCE_DETAILS TO ROLE DEV_ROLE;
