-- contract/intel.sql   DESTRUCTIVE - never run by default.
-- Preconditions: `--mark-cutover intel`, validate/ --strict clean, cutover_compare soak.
-- Rollback: CLONE ${SNAPSHOT}.PLAYER_INFORMATION (loses writes since snapshot).

ALTER TABLE ${CORE}.PLAYER_INFORMATION DROP COLUMN
    CONTACT_NAME, CONTACT_ORGANISATION,
    POTENTIAL_DEAL_TYPE, RELATIONSHIP_TO_PLAYER,
    LENGTH_OF_RELATIONSHIP, RELEVANCE_OF_RELATIONSHIP, REFERENCE_RATING,
    TRANSFER_FEE,
    CURRENT_WAGES, CURRENT_WAGES_MIN, CURRENT_WAGES_MAX,
    EXPECTED_WAGES, EXPECTED_WAGES_MIN, EXPECTED_WAGES_MAX;

-- Dual player reference -> single key.
ALTER TABLE ${CORE}.PLAYER_INFORMATION DROP COLUMN PLAYER_ID, DATA_SOURCE;
ALTER TABLE ${CORE}.PLAYER_INFORMATION RENAME COLUMN CANONICAL_PLAYER_ID TO CAFC_PLAYER_ID;
