-- swap/recommendations_rollback.sql
-- Undo the swap. Anything written to the normalized tables since the swap is copied BACK into the legacy
-- table first (via the compat view, which reproduces the legacy shape), so no writes are lost. Then the
-- original name is restored. The runner also un-marks the cutover so the derived tables can be re-synced.
--
-- After this, the app must be pointed back at the legacy write path (config flag / previous release).

-- Explicit columns: the legacy table also carries LINKED_CANONICAL_PLAYER_ID (added by 021), which the view
-- does not expose, so it is restored from the normalized table.
INSERT OVERWRITE INTO ${CORE}.PLAYER_RECOMMENDATIONS_LEGACY (
    ID, AGENT_NAME, AGENCY, AGENT_EMAIL, AGENT_NUMBER, DATE, TRANSFERMARKT_LINK, AGREEMENT_TYPE,
    CONTRACT_EXPIRY, CONTRACT_OPTIONS, POTENTIAL_DEAL_TYPE, TRANSFER_FEE, CURRENT_WAGES, EXPECTED_WAGES,
    ADDITIONAL_INFO, PLAYER_NAME, SUBMITTED_BY_USER_ID, STATUS, STATUS_UPDATED_AT, STATUS_UPDATED_BY,
    INTERNAL_NOTES, UPDATED_AT, CREATED_AT, EXPECTED_WAGES_CURRENCY, EXPECTED_WAGES_AMOUNT,
    CURRENT_WAGES_CURRENCY, CURRENT_WAGES_AMOUNT, TRANSFER_FEE_CURRENCY, TRANSFER_FEE_AMOUNT,
    RECOMMENDED_POSITION, PLAYER_DATE_OF_BIRTH, AGENT_STATUS, AGENT_STATUS_UPDATED_AT, EXPECTED_WAGES_MAX,
    EXPECTED_WAGES_MIN, CURRENT_WAGES_MAX, CURRENT_WAGES_MIN, WAGE_BASIS, TRANSFER_FEE_MAX, TRANSFER_FEE_MIN,
    LINKED_UNIVERSAL_ID,
    LINKED_CANONICAL_PLAYER_ID
)
SELECT
    v.ID, v.AGENT_NAME, v.AGENCY, v.AGENT_EMAIL, v.AGENT_NUMBER, v.DATE, v.TRANSFERMARKT_LINK,
    v.AGREEMENT_TYPE, v.CONTRACT_EXPIRY, v.CONTRACT_OPTIONS, v.POTENTIAL_DEAL_TYPE, v.TRANSFER_FEE,
    v.CURRENT_WAGES, v.EXPECTED_WAGES, v.ADDITIONAL_INFO, v.PLAYER_NAME, v.SUBMITTED_BY_USER_ID, v.STATUS,
    v.STATUS_UPDATED_AT, v.STATUS_UPDATED_BY, v.INTERNAL_NOTES, v.UPDATED_AT, v.CREATED_AT,
    v.EXPECTED_WAGES_CURRENCY, v.EXPECTED_WAGES_AMOUNT, v.CURRENT_WAGES_CURRENCY, v.CURRENT_WAGES_AMOUNT,
    v.TRANSFER_FEE_CURRENCY, v.TRANSFER_FEE_AMOUNT, v.RECOMMENDED_POSITION, v.PLAYER_DATE_OF_BIRTH,
    v.AGENT_STATUS, v.AGENT_STATUS_UPDATED_AT, v.EXPECTED_WAGES_MAX, v.EXPECTED_WAGES_MIN,
    v.CURRENT_WAGES_MAX, v.CURRENT_WAGES_MIN, v.WAGE_BASIS, v.TRANSFER_FEE_MAX, v.TRANSFER_FEE_MIN,
    v.LINKED_UNIVERSAL_ID,
    r.LINKED_CANONICAL_PLAYER_ID
FROM ${CORE}.V_COMPAT_PLAYER_RECOMMENDATIONS v
JOIN ${CORE}.RECOMMENDATIONS r ON r.ID = v.ID;

ALTER TABLE ${CORE}.RECOMMENDATION_NOTES_HISTORY
    DROP FOREIGN KEY (RECOMMENDATION_ID);

DROP VIEW ${CORE}.PLAYER_RECOMMENDATIONS;

ALTER TABLE ${CORE}.PLAYER_RECOMMENDATIONS_LEGACY RENAME TO ${CORE}.PLAYER_RECOMMENDATIONS;

ALTER TABLE ${CORE}.RECOMMENDATION_NOTES_HISTORY
    ADD FOREIGN KEY (RECOMMENDATION_ID) REFERENCES ${CORE}.PLAYER_RECOMMENDATIONS (ID);
