-- Hard checks: every coded value in the legacy tables exists in its lookup.
-- Zero rows = pass. Each statement selects CHECK_NAME first.

SELECT 'users.role not in ROLES' AS CHECK_NAME, u.ROLE AS VALUE, COUNT(*) AS N
FROM ${CORE}.USERS u
WHERE u.ROLE IS NOT NULL AND u.ROLE NOT IN (SELECT ROLE_CODE FROM ${CORE}.ROLES)
GROUP BY u.ROLE;

SELECT 'scout_reports.report_type not in REPORT_TYPES', TRIM(REPORT_TYPE), COUNT(*)
FROM ${CORE}.SCOUT_REPORTS
WHERE TRIM(REPORT_TYPE) <> '' AND TRIM(REPORT_TYPE) NOT IN (SELECT CODE FROM ${CORE}.REPORT_TYPES)
GROUP BY TRIM(REPORT_TYPE);

SELECT 'scout_reports.purpose not in REPORT_PURPOSES', TRIM(PURPOSE), COUNT(*)
FROM ${CORE}.SCOUT_REPORTS
WHERE TRIM(PURPOSE) <> '' AND TRIM(PURPOSE) NOT IN (SELECT CODE FROM ${CORE}.REPORT_PURPOSES)
GROUP BY TRIM(PURPOSE);

SELECT 'scout_reports.scouting_type not in SCOUTING_TYPES', TRIM(SCOUTING_TYPE), COUNT(*)
FROM ${CORE}.SCOUT_REPORTS
WHERE TRIM(SCOUTING_TYPE) <> '' AND TRIM(SCOUTING_TYPE) NOT IN (SELECT CODE FROM ${CORE}.SCOUTING_TYPES)
GROUP BY TRIM(SCOUTING_TYPE);

SELECT 'scout_reports.flag_category not in FLAG_CATEGORIES', TRIM(FLAG_CATEGORY), COUNT(*)
FROM ${CORE}.SCOUT_REPORTS
WHERE TRIM(FLAG_CATEGORY) <> '' AND TRIM(FLAG_CATEGORY) NOT IN (SELECT CODE FROM ${CORE}.FLAG_CATEGORIES)
GROUP BY TRIM(FLAG_CATEGORY);

SELECT 'scout_reports.clip_category not in CLIP_CATEGORIES', TRIM(CLIP_CATEGORY), COUNT(*)
FROM ${CORE}.SCOUT_REPORTS
WHERE TRIM(CLIP_CATEGORY) <> '' AND TRIM(CLIP_CATEGORY) NOT IN (SELECT CODE FROM ${CORE}.CLIP_CATEGORIES)
GROUP BY TRIM(CLIP_CATEGORY);

SELECT 'player_lists.list_category not in LIST_CATEGORIES', TRIM(LIST_CATEGORY), COUNT(*)
FROM ${CORE}.PLAYER_LISTS
WHERE TRIM(LIST_CATEGORY) <> '' AND TRIM(LIST_CATEGORY) NOT IN (SELECT CODE FROM ${CORE}.LIST_CATEGORIES)
GROUP BY TRIM(LIST_CATEGORY);

SELECT 'player_list_items.stage not in LIST_STAGES', TRIM(STAGE), COUNT(*)
FROM ${CORE}.PLAYER_LIST_ITEMS
WHERE TRIM(STAGE) <> '' AND TRIM(STAGE) NOT IN (SELECT CODE FROM ${CORE}.LIST_STAGES)
GROUP BY TRIM(STAGE);

SELECT 'player_recommendations.status not in RECOMMENDATION_STATUSES', TRIM(STATUS), COUNT(*)
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE TRIM(STATUS) <> '' AND TRIM(STATUS) NOT IN (SELECT CODE FROM ${CORE}.RECOMMENDATION_STATUSES)
GROUP BY TRIM(STATUS);

SELECT 'player_information.intel_type not in INTEL_TYPES', TRIM(INTEL_TYPE), COUNT(*)
FROM ${CORE}.PLAYER_INFORMATION
WHERE TRIM(INTEL_TYPE) <> '' AND TRIM(INTEL_TYPE) NOT IN (SELECT CODE FROM ${CORE}.INTEL_TYPES)
GROUP BY TRIM(INTEL_TYPE);

-- Unenforced primary keys on the lookups themselves.
SELECT 'lookup duplicate key: ROLES', ROLE_CODE, COUNT(*) FROM ${CORE}.ROLES GROUP BY ROLE_CODE HAVING COUNT(*) > 1;
SELECT 'lookup duplicate key: LIST_STAGES', CODE, COUNT(*) FROM ${CORE}.LIST_STAGES GROUP BY CODE HAVING COUNT(*) > 1;
SELECT 'lookup duplicate key: DEAL_TYPES', CODE, COUNT(*) FROM ${CORE}.DEAL_TYPES GROUP BY CODE HAVING COUNT(*) > 1;
