-- Hard checks for AGENCIES / AGENTS and the links to them.

SELECT 'AGENTS duplicate AGENT_KEY' AS CHECK_NAME, AGENT_KEY AS VALUE, COUNT(*) AS N
FROM ${CORE}.AGENTS GROUP BY AGENT_KEY HAVING COUNT(*) > 1;

SELECT 'AGENCIES duplicate AGENCY_KEY', AGENCY_KEY, COUNT(*)
FROM ${CORE}.AGENCIES GROUP BY AGENCY_KEY HAVING COUNT(*) > 1;

SELECT 'AGENTS.agency_id orphan', TO_VARCHAR(AGENT_ID), 1
FROM ${CORE}.AGENTS
WHERE AGENCY_ID IS NOT NULL AND AGENCY_ID NOT IN (SELECT AGENCY_ID FROM ${CORE}.AGENCIES);

SELECT 'player_recommendations.agent_id orphan', TO_VARCHAR(ID), 1
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE AGENT_ID IS NOT NULL AND AGENT_ID NOT IN (SELECT AGENT_ID FROM ${CORE}.AGENTS);

SELECT 'player_recommendations has agent facts but no agent_id', TO_VARCHAR(ID), 1
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE AGENT_ID IS NULL
  AND ${CORE}.AGENT_KEY(AGENT_NAME, AGENCY, AGENT_EMAIL) IS NOT NULL;

SELECT 'agent_profiles.agent_id orphan', TO_VARCHAR(USER_ID), 1
FROM ${CORE}.AGENT_PROFILES
WHERE AGENT_ID IS NOT NULL AND AGENT_ID NOT IN (SELECT AGENT_ID FROM ${CORE}.AGENTS);
