-- Hard checks for AGENCIES and the link from AGENT_PROFILES.

SELECT 'AGENCIES duplicate AGENCY_KEY' AS CHECK_NAME, AGENCY_KEY AS VALUE, COUNT(*) AS N
FROM ${CORE}.AGENCIES GROUP BY AGENCY_KEY HAVING COUNT(*) > 1;

SELECT 'agent_profiles.agency_id orphan', TO_VARCHAR(USER_ID), 1
FROM ${CORE}.AGENT_PROFILES
WHERE AGENCY_ID IS NOT NULL AND AGENCY_ID NOT IN (SELECT AGENCY_ID FROM ${CORE}.AGENCIES);

SELECT 'agent_profiles names an agency but has no agency_id', TO_VARCHAR(USER_ID), 1
FROM ${CORE}.AGENT_PROFILES
WHERE AGENCY_ID IS NULL AND ${CORE}.NORMALIZE_NAME_KEY(AGENCY) IS NOT NULL;
