-- Hard checks: derived recommendation tables are complete and consistent with the source.

SELECT 'RECOMMENDATION_TERMS duplicate (recommendation, term)' AS CHECK_NAME, RECOMMENDATION_ID AS ROW_ID, COUNT(*) AS N
FROM ${CORE}.RECOMMENDATION_TERMS GROUP BY RECOMMENDATION_ID, TERM_TYPE HAVING COUNT(*) > 1;

SELECT 'RECOMMENDATION_TERMS orphan', RECOMMENDATION_ID, 1
FROM ${CORE}.RECOMMENDATION_TERMS
WHERE RECOMMENDATION_ID NOT IN (SELECT ID FROM ${CORE}.PLAYER_RECOMMENDATIONS);

SELECT 'RECOMMENDATION_TERMS.term_type invalid', TERM_TYPE, COUNT(*)
FROM ${CORE}.RECOMMENDATION_TERMS
WHERE TERM_TYPE NOT IN ('TRANSFER_FEE', 'CURRENT_WAGES', 'EXPECTED_WAGES')
GROUP BY TERM_TYPE;

SELECT 'RECOMMENDATION_TERMS.amount outside [min,max]', RECOMMENDATION_ID, 1
FROM ${CORE}.RECOMMENDATION_TERMS
WHERE AMOUNT_MIN IS NOT NULL AND AMOUNT_MAX IS NOT NULL AND AMOUNT_MIN > AMOUNT_MAX;

-- Every legacy amount survived: source rows with a transfer fee number vs term rows.
SELECT 'RECOMMENDATION_TERMS missing TRANSFER_FEE rows', src.N - COALESCE(t.N, 0), 1
FROM (SELECT COUNT(*) AS N FROM ${CORE}.PLAYER_RECOMMENDATIONS
      WHERE COALESCE(TRANSFER_FEE_AMOUNT, TRANSFER_FEE_MIN, TRANSFER_FEE_MAX) IS NOT NULL
         OR NULLIF(TRIM(TO_VARCHAR(TRANSFER_FEE)), '') IS NOT NULL) src,
     (SELECT COUNT(*) AS N FROM ${CORE}.RECOMMENDATION_TERMS WHERE TERM_TYPE = 'TRANSFER_FEE') t
WHERE src.N <> COALESCE(t.N, 0);

SELECT 'RECOMMENDATION_DEAL_TYPES duplicate', RECOMMENDATION_ID, COUNT(*)
FROM ${CORE}.RECOMMENDATION_DEAL_TYPES GROUP BY RECOMMENDATION_ID, DEAL_TYPE_CODE HAVING COUNT(*) > 1;

SELECT 'RECOMMENDATION_DEAL_TYPES orphan', RECOMMENDATION_ID, 1
FROM ${CORE}.RECOMMENDATION_DEAL_TYPES
WHERE RECOMMENDATION_ID NOT IN (SELECT ID FROM ${CORE}.PLAYER_RECOMMENDATIONS);

SELECT 'RECOMMENDATION_DEAL_TYPES code not in DEAL_TYPES', DEAL_TYPE_CODE, COUNT(*)
FROM ${CORE}.RECOMMENDATION_DEAL_TYPES
WHERE DEAL_TYPE_CODE NOT IN (SELECT CODE FROM ${CORE}.DEAL_TYPES)
GROUP BY DEAL_TYPE_CODE;

-- The split lost nothing: recommendations with a deal-type string but no junction rows.
SELECT 'recommendations with POTENTIAL_DEAL_TYPE but no junction rows', r.ID, 1
FROM ${CORE}.PLAYER_RECOMMENDATIONS r
WHERE NULLIF(TRIM(r.POTENTIAL_DEAL_TYPE), '') IS NOT NULL
  AND r.ID NOT IN (SELECT RECOMMENDATION_ID FROM ${CORE}.RECOMMENDATION_DEAL_TYPES);
