-- Hard checks: contacts and the normalized intel tables are complete and consistent.

SELECT 'CONTACTS duplicate CONTACT_KEY' AS CHECK_NAME, CONTACT_KEY AS VALUE, COUNT(*) AS N
FROM ${CORE}.CONTACTS GROUP BY CONTACT_KEY HAVING COUNT(*) > 1;

SELECT 'INTEL_REPORTS duplicate ID', TO_VARCHAR(ID), COUNT(*)
FROM ${CORE}.INTEL_REPORTS GROUP BY ID HAVING COUNT(*) > 1;

SELECT 'INTEL_REPORTS.contact_id orphan', TO_VARCHAR(ID), 1
FROM ${CORE}.INTEL_REPORTS
WHERE CONTACT_ID IS NOT NULL AND CONTACT_ID NOT IN (SELECT CONTACT_ID FROM ${CORE}.CONTACTS);

SELECT 'INTEL_REPORTS.intel_type not in INTEL_TYPES', TO_VARCHAR(ID), 1
FROM ${CORE}.INTEL_REPORTS
WHERE INTEL_TYPE NOT IN (SELECT CODE FROM ${CORE}.INTEL_TYPES);

SELECT 'INTEL_TERMS duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_TERMS GROUP BY INTEL_REPORT_ID, TERM_TYPE HAVING COUNT(*) > 1;

SELECT 'INTEL_TERMS orphan', TO_VARCHAR(INTEL_REPORT_ID), 1
FROM ${CORE}.INTEL_TERMS WHERE INTEL_REPORT_ID NOT IN (SELECT ID FROM ${CORE}.INTEL_REPORTS);

SELECT 'INTEL_DEAL_TYPES duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_DEAL_TYPES GROUP BY INTEL_REPORT_ID, DEAL_TYPE_CODE HAVING COUNT(*) > 1;

SELECT 'INTEL_DEAL_TYPES orphan', TO_VARCHAR(INTEL_REPORT_ID), 1
FROM ${CORE}.INTEL_DEAL_TYPES WHERE INTEL_REPORT_ID NOT IN (SELECT ID FROM ${CORE}.INTEL_REPORTS);

SELECT 'INTEL_RELATIONSHIPS duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_RELATIONSHIPS GROUP BY INTEL_REPORT_ID, RELATIONSHIP_CODE HAVING COUNT(*) > 1;

SELECT 'INTEL_RELATIONSHIPS orphan', TO_VARCHAR(INTEL_REPORT_ID), 1
FROM ${CORE}.INTEL_RELATIONSHIPS WHERE INTEL_REPORT_ID NOT IN (SELECT ID FROM ${CORE}.INTEL_REPORTS);

SELECT 'INTEL_REFERENCE_DETAILS duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_REFERENCE_DETAILS GROUP BY INTEL_REPORT_ID HAVING COUNT(*) > 1;

SELECT 'INTEL_REFERENCE_DETAILS orphan or not a reference_form', TO_VARCHAR(d.INTEL_REPORT_ID), 1
FROM ${CORE}.INTEL_REFERENCE_DETAILS d
LEFT JOIN ${CORE}.INTEL_REPORTS r ON r.ID = d.INTEL_REPORT_ID
WHERE r.ID IS NULL OR r.INTEL_TYPE <> 'reference_form';

SELECT 'reference_form intel without reference details', TO_VARCHAR(r.ID), 1
FROM ${CORE}.INTEL_REPORTS r
WHERE r.INTEL_TYPE = 'reference_form'
  AND r.ID NOT IN (SELECT INTEL_REPORT_ID FROM ${CORE}.INTEL_REFERENCE_DETAILS);
