-- Hard checks: contacts and derived intel tables are complete and consistent.

SELECT 'CONTACTS duplicate CONTACT_KEY' AS CHECK_NAME, CONTACT_KEY AS VALUE, COUNT(*) AS N
FROM ${CORE}.CONTACTS GROUP BY CONTACT_KEY HAVING COUNT(*) > 1;

SELECT 'player_information.contact_id orphan', TO_VARCHAR(ID), 1
FROM ${CORE}.PLAYER_INFORMATION
WHERE CONTACT_ID IS NOT NULL AND CONTACT_ID NOT IN (SELECT CONTACT_ID FROM ${CORE}.CONTACTS);

SELECT 'player_information has contact name but no contact_id', TO_VARCHAR(ID), 1
FROM ${CORE}.PLAYER_INFORMATION
WHERE CONTACT_ID IS NULL AND ${CORE}.NORMALIZE_NAME_KEY(CONTACT_NAME) IS NOT NULL;

SELECT 'INTEL_TERMS duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_TERMS GROUP BY INTEL_REPORT_ID, TERM_TYPE HAVING COUNT(*) > 1;

SELECT 'INTEL_TERMS orphan', TO_VARCHAR(INTEL_REPORT_ID), 1
FROM ${CORE}.INTEL_TERMS WHERE INTEL_REPORT_ID NOT IN (SELECT ID FROM ${CORE}.PLAYER_INFORMATION);

SELECT 'INTEL_DEAL_TYPES duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_DEAL_TYPES GROUP BY INTEL_REPORT_ID, DEAL_TYPE_CODE HAVING COUNT(*) > 1;

SELECT 'INTEL_RELATIONSHIPS duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_RELATIONSHIPS GROUP BY INTEL_REPORT_ID, RELATIONSHIP_CODE HAVING COUNT(*) > 1;

SELECT 'INTEL_REFERENCE_DETAILS duplicate', TO_VARCHAR(INTEL_REPORT_ID), COUNT(*)
FROM ${CORE}.INTEL_REFERENCE_DETAILS GROUP BY INTEL_REPORT_ID HAVING COUNT(*) > 1;

SELECT 'intel with deal-type string but no junction rows', TO_VARCHAR(i.ID), 1
FROM ${CORE}.PLAYER_INFORMATION i
WHERE NULLIF(TRIM(i.POTENTIAL_DEAL_TYPE), '') IS NOT NULL
  AND i.ID NOT IN (SELECT INTEL_REPORT_ID FROM ${CORE}.INTEL_DEAL_TYPES);

SELECT 'intel with relationship string but no junction rows', TO_VARCHAR(i.ID), 1
FROM ${CORE}.PLAYER_INFORMATION i
WHERE NULLIF(TRIM(i.RELATIONSHIP_TO_PLAYER), '') IS NOT NULL
  AND i.ID NOT IN (SELECT INTEL_REPORT_ID FROM ${CORE}.INTEL_RELATIONSHIPS);

SELECT 'reference_form intel without reference details', TO_VARCHAR(i.ID), 1
FROM ${CORE}.PLAYER_INFORMATION i
WHERE i.INTEL_TYPE = 'reference_form'
  AND i.ID NOT IN (SELECT INTEL_REPORT_ID FROM ${CORE}.INTEL_REFERENCE_DETAILS);
