-- Informational: lookup rows that came from the data (not the code constants) and are still
-- inactive. Each needs a human decision: fix the data, `UPDATE <lookup> SET IS_ACTIVE = TRUE`
-- to keep the value, or delete the row once no data uses it. Clears as they are decided.

SELECT 'REPORT_TYPES' AS LOOKUP, CODE, ORIGIN FROM ${CORE}.REPORT_TYPES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'REPORT_PURPOSES', CODE, ORIGIN FROM ${CORE}.REPORT_PURPOSES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'SCOUTING_TYPES', CODE, ORIGIN FROM ${CORE}.SCOUTING_TYPES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'FLAG_CATEGORIES', CODE, ORIGIN FROM ${CORE}.FLAG_CATEGORIES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'CLIP_CATEGORIES', CODE, ORIGIN FROM ${CORE}.CLIP_CATEGORIES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'LIST_CATEGORIES', CODE, ORIGIN FROM ${CORE}.LIST_CATEGORIES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'LIST_STAGES', CODE, ORIGIN FROM ${CORE}.LIST_STAGES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'RECOMMENDATION_STATUSES', CODE, ORIGIN FROM ${CORE}.RECOMMENDATION_STATUSES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'INTEL_TYPES', CODE, ORIGIN FROM ${CORE}.INTEL_TYPES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'DEAL_TYPES', CODE, ORIGIN FROM ${CORE}.DEAL_TYPES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE
UNION ALL SELECT 'RELATIONSHIP_TYPES', CODE, ORIGIN FROM ${CORE}.RELATIONSHIP_TYPES WHERE ORIGIN = 'DATA' AND IS_ACTIVE = FALSE;
