-- Informational (promoted to failures by --strict, the gate for app cutover):
-- rows that carry a legacy id but could not be given a canonical key.

SELECT 'scout_reports: player unresolved' AS CHECK_NAME, COUNT(*) AS N
FROM ${CORE}.SCOUT_REPORTS
WHERE CANONICAL_PLAYER_ID IS NULL AND (PLAYER_ID IS NOT NULL OR CAFC_PLAYER_ID IS NOT NULL)
HAVING COUNT(*) > 0;

SELECT 'scout_reports: fixture unresolved', COUNT(*)
FROM ${CORE}.SCOUT_REPORTS
WHERE CANONICAL_FIXTURE_ID IS NULL AND MATCH_ID IS NOT NULL
HAVING COUNT(*) > 0;

-- MATCH_ID that is BOTH an IMPECT match id and a manual fixture's CAFC id (left NULL on purpose).
SELECT 'scout_reports: ambiguous MATCH_ID', sr.ID, sr.MATCH_ID
FROM ${CORE}.SCOUT_REPORTS sr
WHERE sr.MATCH_ID IS NOT NULL
  AND TO_VARCHAR(sr.MATCH_ID) IN (
      SELECT SOURCE_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
      WHERE SOURCE_SYSTEM = 'IMPECT' AND SOURCE_FIXTURE_ID IS NOT NULL)
  AND sr.MATCH_ID IN (
      SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURES
      WHERE CAFC_FIXTURE_ID NOT IN (
          SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
          WHERE SOURCE_SYSTEM = 'IMPECT' AND CAFC_FIXTURE_ID IS NOT NULL));

SELECT 'player_list_items: player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_LIST_ITEMS
WHERE CANONICAL_PLAYER_ID IS NULL AND (PLAYER_ID IS NOT NULL OR CAFC_PLAYER_ID IS NOT NULL)
HAVING COUNT(*) > 0;

SELECT 'player_information: player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_INFORMATION
WHERE CANONICAL_PLAYER_ID IS NULL AND PLAYER_ID IS NOT NULL
HAVING COUNT(*) > 0;

SELECT 'player_list_flags: player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_LIST_FLAGS
WHERE CAFC_PLAYER_ID IS NULL AND UNIVERSAL_ID IS NOT NULL
HAVING COUNT(*) > 0;

SELECT 'player_recommendations: linked player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE LINKED_CAFC_PLAYER_ID IS NULL AND LINKED_UNIVERSAL_ID IS NOT NULL
HAVING COUNT(*) > 0;
