-- Informational (promoted to failures by --strict, the gate for app cutover):
-- rows that carry a legacy id but could not be given a canonical key.

SELECT 'scout_reports: player unresolved' AS CHECK_NAME, COUNT(*) AS N
FROM ${CORE}.SCOUT_REPORTS
WHERE CANONICAL_PLAYER_ID IS NULL AND (PLAYER_ID IS NOT NULL OR CAFC_PLAYER_ID IS NOT NULL)
HAVING COUNT(*) > 0;

SELECT 'scout_reports: fixture unresolved', COUNT(*)
FROM ${CORE}.SCOUT_REPORTS
WHERE CANONICAL_FIXTURE_ID IS NULL AND MATCH_ID IS NOT NULL
HAVING COUNT(*) > 0;

-- MATCH_ID that is BOTH an IMPECT match id and a manual fixture's CAFC id (left NULL on purpose).
SELECT 'scout_reports: ambiguous MATCH_ID', sr.ID, sr.MATCH_ID
FROM ${CORE}.SCOUT_REPORTS sr
WHERE sr.MATCH_ID IS NOT NULL
  AND TO_VARCHAR(sr.MATCH_ID) IN (
      SELECT SOURCE_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
      WHERE SOURCE_SYSTEM = 'IMPECT' AND SOURCE_FIXTURE_ID IS NOT NULL)
  AND sr.MATCH_ID IN (
      SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURES
      WHERE CAFC_FIXTURE_ID NOT IN (
          SELECT CAFC_FIXTURE_ID FROM ${CORE}.FIXTURE_IDENTITIES
          WHERE SOURCE_SYSTEM = 'IMPECT' AND CAFC_FIXTURE_ID IS NOT NULL));

SELECT 'player_list_items: player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_LIST_ITEMS
WHERE CANONICAL_PLAYER_ID IS NULL AND (PLAYER_ID IS NOT NULL OR CAFC_PLAYER_ID IS NOT NULL)
HAVING COUNT(*) > 0;

SELECT 'player_information: player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_INFORMATION
WHERE CANONICAL_PLAYER_ID IS NULL AND PLAYER_ID IS NOT NULL
HAVING COUNT(*) > 0;

SELECT 'player_list_flags: player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_LIST_FLAGS
WHERE CAFC_PLAYER_ID IS NULL AND UNIVERSAL_ID IS NOT NULL
HAVING COUNT(*) > 0;

SELECT 'player_recommendations: linked player unresolved', COUNT(*)
FROM ${CORE}.PLAYER_RECOMMENDATIONS
WHERE LINKED_CANONICAL_PLAYER_ID IS NULL AND LINKED_UNIVERSAL_ID IS NOT NULL
HAVING COUNT(*) > 0;

-- ---- STALE keys: the legacy columns are still the source of truth until cutover -------------
-- Non-zero after a merge / remap / identity override until the 02x sync files are re-run.
SELECT 'STALE scout_reports canonical keys' AS CHECK_NAME, COUNT(*) AS N
FROM ${CORE}.SCOUT_REPORTS t JOIN ${CORE}.V_SCOUT_REPORT_KEYS k ON k.ID = t.ID
WHERE t.CANONICAL_PLAYER_ID IS DISTINCT FROM k.EXPECTED_PLAYER_ID
   OR t.CANONICAL_FIXTURE_ID IS DISTINCT FROM k.EXPECTED_FIXTURE_ID
HAVING COUNT(*) > 0;

SELECT 'STALE player_list_items canonical key', COUNT(*)
FROM ${CORE}.PLAYER_LIST_ITEMS t JOIN ${CORE}.V_PLAYER_LIST_ITEM_KEYS k ON k.ID = t.ID
WHERE t.CANONICAL_PLAYER_ID IS DISTINCT FROM k.EXPECTED_PLAYER_ID
HAVING COUNT(*) > 0;

SELECT 'STALE player_list_flags key', COUNT(*)
FROM ${CORE}.PLAYER_LIST_FLAGS t JOIN ${CORE}.V_PLAYER_LIST_FLAG_KEYS k ON k.UNIVERSAL_ID = t.UNIVERSAL_ID
WHERE t.CAFC_PLAYER_ID IS DISTINCT FROM k.EXPECTED_PLAYER_ID
HAVING COUNT(*) > 0;

SELECT 'STALE recommendation linked key', COUNT(*)
FROM ${CORE}.PLAYER_RECOMMENDATIONS t JOIN ${CORE}.V_RECOMMENDATION_KEYS k ON k.ID = t.ID
WHERE t.LINKED_CANONICAL_PLAYER_ID IS DISTINCT FROM k.EXPECTED_PLAYER_ID
HAVING COUNT(*) > 0;

SELECT 'STALE intel canonical key', COUNT(*)
FROM ${CORE}.PLAYER_INFORMATION t JOIN ${CORE}.V_INTEL_KEYS k ON k.ID = t.ID
WHERE t.CANONICAL_PLAYER_ID IS DISTINCT FROM k.EXPECTED_PLAYER_ID
HAVING COUNT(*) > 0;

-- ---- keys that point at a RETIRED player (platform merges set IS_ACTIVE = FALSE) ----------
-- The keeper should be used instead. Zero today; matters once merges land.
SELECT 'canonical key points at a retired player: ' || src AS CHECK_NAME, COUNT(*) AS N
FROM (
    SELECT 'scout_reports' AS src, CANONICAL_PLAYER_ID AS pid FROM ${CORE}.SCOUT_REPORTS
    UNION ALL SELECT 'player_list_items', CANONICAL_PLAYER_ID FROM ${CORE}.PLAYER_LIST_ITEMS
    UNION ALL SELECT 'player_information', CANONICAL_PLAYER_ID FROM ${CORE}.PLAYER_INFORMATION
    UNION ALL SELECT 'player_list_flags', CAFC_PLAYER_ID FROM ${CORE}.PLAYER_LIST_FLAGS
    UNION ALL SELECT 'player_recommendations', LINKED_CANONICAL_PLAYER_ID FROM ${CORE}.PLAYER_RECOMMENDATIONS
) x
JOIN ${CORE}.PLAYERS p ON p.CAFC_PLAYER_ID = x.pid
WHERE p.IS_ACTIVE = FALSE
GROUP BY src;
